### ISSUE TITLE
Response Time and Throughput

### ISSUE THREAD

**Issue by KiarashS** [shoreditch-ops/artillery#101]
Dear,

Very thanks for artillery.
How we can access **Average Response Time** and **Throughput** in artillery?

Thanks in advance.

**Comment by hassy** [comment]
@KiarashS In Artillery's report throughput is RPS (requests per second), average response time is not reported (it's useless) but the closest to that is median latency.

**Comment by KiarashS** [comment]
How i can access Throughput in MB/s?

**Comment by hassy** [comment]
That's not reported yet, created https://github.com/shoreditch-ops/artillery/issues/102
