### ISSUE TITLE
Docs: document the new socket.io engine

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#103]
We have a socket.io engine now thanks to @ksplache and now it needs to be documented.

**Comment by ksplache** [comment]
Here is the short version of the docs:
The engine is ```socketio```
The ```emit``` command takes an object as its parameter:
+ emit
  + channel – the name of the socket.io channel to emit to
  + data – the data to emit
  + response – optional object if you want to wait for a response
    + channel – the name of the channel where the response is received
    + data – the data to verify is in the response (though I don’t think this verification is working very well)

```
{
      "engine": "socketio",
      "flow": [
        {"emit": { "channel": "echo", "data": "hello", "response": { "channel": "echoed", "data": "hello"} }},
        {"emit": { "channel": "echo", "data": "world", "response": { "channel": "echoed", "data": "world"} }},
        {"think": 1},
        {"emit": { "channel": "echo", "data": "do not care about the response" }},
        {"emit": { "channel": "echo", "data": "still do not care about the response" }},
        {"think": 1}
      ]
}
```

**Comment by ksplache** [comment]
Also, you can combine ```http``` and ```socketio``` requests in the artillery JSON file when a server supports both.  This is common when using express.

```
{
  "config": {
      "target": "http://127.0.0.1:9092",
      "phases": [
        {"duration": 10, "arrivalRate": 1}
      ]
  },
  "scenarios": [
    {
      "flow": [
        {"get": { "url": "/test" }}
      ]
    },
    {
      "engine": "socketio",
      "flow": [
        {"emit": { "channel": "echo", "data": "hello", "response": { "channel": "echoed", "data": "hello"} }},
        {"emit": { "channel": "echo", "data": "world", "response": { "channel": "echoed", "data": "world"} }},
        {"think": 1},
        {"emit": { "channel": "echo", "data": "do not care about the response" }},
        {"emit": { "channel": "echo", "data": "still do not care about the response" }},
        {"think": 1}
      ]
    }
  ]
}
```

**Comment by hassy** [comment]
This is great, thanks @ksplache!

**Comment by CharlesJu1** [comment]
This is great. But I am having a problem using it. The nodejs server does not get socketio connection. The wireshark capture shows socketio is setup using both polling and websocket. However, in the polling, the connection header is set to "close". When I test the socket io with chrome client, the connection header is set to "keep alive". On the nodejs server side, I log a message when there is socket io connection setup. I am attaching the wireshark capture file and the artillery file. In the wireshark file, 10.154.14.5 is the nodejs server, 10.154.14.35 is the client. 

[BusStopRegister.zip](https://github.com/shoreditch-ops/artillery/files/285733/BusStopRegister.zip)

**Comment by hassy** [comment]
@CharlesJu1 no time to look into right now, but have you tried `v1.5.0-1`?

https://github.com/shoreditch-ops/artillery/releases/tag/1.5.0-1

**Comment by ksplache** [comment]
@CharlesJu1 can you post a code snippet of your nodejs code that is listening on socket.io?

There are example nodejs servers here:
https://github.com/shoreditch-ops/artillery-core/blob/master/test/targets/simple_socketio.js
https://github.com/shoreditch-ops/artillery-core/blob/master/test/targets/express_socketio.js

With the corresponding artillery files here:
https://github.com/shoreditch-ops/artillery-core/blob/master/test/scripts/hello_socketio.json
https://github.com/shoreditch-ops/artillery-core/blob/master/test/scripts/express_socketio.json

It also might be helpful to turn on the nodejs server's socket.io debugging via ```NODE_DEBUG="socket*"``` or setting ```process.env.debug = "socket*";``` in the js code.

**Comment by CharlesJu1** [comment]
v1.5.0-4  works.

**Comment by almircajic** [comment]
Hi @ksplache 

Im using latest version 1.5.0-8 and connecting and emitting messages all seem to work great - even in combination with url posts and gets. Great work indeed!

However, with engine set as socketio, I'm getting error if I use functions such as randomNumber or randomString. Both work as expected if I change the engine to default (and remove any emits of course).

The error is thrown in engine_util.js (from the artillery-core) line 109:
```javascript
if (funcName in context.funcs) {
      return template(o.replace(funcCallRegex, context.funcs[funcName].apply(null, args)), context);
}
```
Error description is:
```
TypeError: Cannot use 'in' operator to search for '$randomNumber' in undefined
```
After debugging, it seems that context passed to the "template" function is there containing socketio key, but it does not seem to have funcs list attached to it. 

Appreciate your help on this.

**Comment by ksplache** [comment]
I'll take a look at it.  The socketio engine template processing likely needs to be updated to handle those keywords / functions.

**Comment by ksplache** [comment]
I've fixed the issue and submitted an MR.
https://github.com/shoreditch-ops/artillery-core/pull/72

**Comment by almircajic** [comment]
Hi @ksplache 

New patch works great! Thanks so much for this super-fast fix. Both, $randomString and $randomNumber functions can now be used with socketio engine.

**Comment by hassy** [comment]
@ksplache @almircajic Just published `v1.5.0-10` with the fix ✨

**Comment by hassy** [comment]
The Socket.io docs are up!

https://artillery.io/docs/testing_socketio.html

Source:
https://github.com/shoreditch-ops/artillery-docs/blob/master/source/testing_socketio.rst

**Comment by varun10221** [comment]
Hi,
How do i Send Json objects as Data while checking socket io?

Eg:
Channel: emit
Data: "I want Json data instead of string"

**Comment by ksplache** [comment]
You can either put the JSON there directly or put in a string that contains the JSON.  Examples:

```
"emit": {
    "channel": "firstchannel",
    "data": [
        { "obj1_key1": "obj1_value1", "obj1_key2": "obj1_value2" },
        { "obj2_key1": "obj2_value1", "obj2_key2": "obj2_value2" }
    ]
}

"emit": {
    "channel": "mychannel",
    "data": "[ \"array_item1\",  \"array_item2\" ]" 
} 

```

**Comment by panjizeith** [comment]
Hi, how do I simulate load testing artillery to hit random socket ID in single run ?

**Comment by hassy** [comment]
@panjizeith can you create a new issue please - this one is not the appropriate place for a question. Can you provide a bit more information too - what do you mean by "hit random socket ID"?

**Comment by panjizeith** [comment]
@hassy already post the new issue, sorry for the mistake
