### ISSUE TITLE
Incorrect report name when using --output switch

### ISSUE THREAD

**Issue by tonymcbeth** [shoreditch-ops/artillery#117]
When running the following CLI command

`artillery run --output results.json`

I get the output filename 'Log file: r444u6/23/2016t44.j44on'. This works fine when using the shorthand -o switch

**Comment by hassy** [comment]
Thanks for the report @tonymcbeth, can confirm it's a bug

**Comment by hassy** [comment]
Fixed in `v1.5.0-14`
