### ISSUE TITLE
Does this support WSS?

### ISSUE THREAD

**Issue by morrislaptop** [shoreditch-ops/artillery#119]

**Comment by hassy** [comment]
Yes ([ws](https://github.com/websockets/ws) is used under the hood)

**Comment by morrislaptop** [comment]
Does it work with SockJS, I can't get this to work? :(

**Comment by hassy** [comment]
It should but you have to connect directly to the WebSocket endpoint, and also IIRC SockJS has its own protocol on top of WebSockets, so you can't just send messages like with a plain WS connection.
