### ISSUE TITLE
How do I send JSON in WS message?

### ISSUE THREAD

**Issue by lalarsson** [shoreditch-ops/artillery#124]
As written in title.

**Comment by hassy** [comment]
@lalarsson something like this?

```javascript
{"send": "{\"mykey\":\"myvalue\"}"}
```

**Comment by danielmihai** [comment]
Did this work? 
I'm going to test JSON-RPC over WebSockets. I'm going to try this and come back with a response myself.

**Comment by yamanaltereh** [comment]
@danielmihai any response? how we can send json?

**Comment by utkarsh1097** [comment]
7 years late but it can be done using `flow.send`
