### ISSUE TITLE
A way to call JavaScript from the page or interact with an element?

### ISSUE THREAD

**Issue by jdarling** [shoreditch-ops/artillery#125]
Is their any way in Artillery to interact with the page(s)?  Such as click a log out link or execute the logout method of some global object?

We don't currently have a logout route that we can call currently so would like to just call the logout handler.

**Comment by hassy** [comment]
No, Artillery's HTTP engine only does HTTP - it doesn't evaluate the HTML or run in-page JS.

It should be possible to write a PhantomJS-based engine that would make Artillery act like a browser, but it's not on the roadmap yet. As always, PRs would be very gladly received though!
