### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by jdarling** [shoreditch-ops/artillery#126]
One more idea, how about a containerized version that would allow you to spin up workers in Docker?

I've been doing a lot of work in Docker and Kubernetes lately and will probably be doing this for my own use anyways.  If I get it easy to use do you want it?

**Comment by hassy** [comment]
It's easy enough to run Artillery in a Docker container already. By spinning up workers do you mean running multiple instances of Artillery to run distributed tests? Doing distribution right (spliting up the work among workers evenly, aggregating and merging stats correctly etc) needs to be done in Artillery itself - neither Docker not Kubernetes can provide that for free as far as I can see. I'd be very curious to see anything you might come up with though!
