### ISSUE TITLE
[Feature Request] Response Header Parser 

### ISSUE THREAD

**Issue by danielmihai** [shoreditch-ops/artillery#133]
Hi @hassy ,

It would be nice to have a response headers parser and variable creator as you do on the response body, to include/pass on to other requests in the flow. Do you think this can be done ? 

I offer you my help, if you don't have time to implement and integrate this change. 

Thank you,
Daniel M. Colceag.

**Comment by hassy** [comment]
It's already possible to capture response headers with something like:

```javascript
{"get": {"url": "/", "capture": {"header": "x-some-header", "as": "myheader"}}
```

Going to document it now! :)
