### ISSUE TITLE
Wrong post example

### ISSUE THREAD

**Issue by danielo515** [shoreditch-ops/artillery#134]
Hello, the following example on the payloads section seems to be wront:

```json
"scenarios": [
    {
      "post": "/auth",
      "json": {
        "username": "{{ username }}",
        "password": "{{ password }}"
      }
    }
  ]
```

If I don't include a flow array it fails. I would like to use that syntax for the sake of simplicity. Is it a bad example or I'm doing something wrong?

**Comment by hassy** [comment]
You're right @danielo515 , that example is wrong, sorry!
