### ISSUE TITLE
add website to repo , or own repo

### ISSUE THREAD

**Issue by DannyCork** [shoreditch-ops/artillery#137]
I'd like to contribute to updating artillery's documentation. I believe all the docs are on the website so I'm out of luck?

If the website was on Github as a separate repo anyone could update the docs with a pr .Maybe https://readthedocs.org/ is a better alternative as there is no redeployment of website required when the docs update?

**Comment by hassy** [comment]
Yup, new Sphinx-based docs are coming soon. :)

**Comment by hassy** [comment]
@DannyCork Sources for the new docs are here: https://github.com/shoreditch-ops/artillery-docs :)
