### ISSUE TITLE
How does artillery tool make HTTP requests?

### ISSUE THREAD

**Issue by rvnath** [shoreditch-ops/artillery#138]
OK.  If I am using this tool for load testing of a HTTP server, I wanna know if it reuses the tcp connections for multiple requests, or does it follow the setup, user and tear-down approach for each request?

The reason I am asking this is because the behavior I observed in my NodeJS+EspressJS web server. Once the loading (RPS) crosses 500, it starts getting in **enobufs** error.  I am trying to google for a solution, but not yet close to it :(-.

Can I get more info on this error and what I should be doing to avoid this error...

**Comment by hassy** [comment]
By default Artillery will open a new TCP connection for each *virtual user* (which will usually make multiple requests over that connection).

You can set the maximum total number of connections with `config.http.pool`. That will make multiple virtual users reuse the same connection.

**Comment by rvnath** [comment]
Thanks for the info.  For my particular problem, I tried looking up at this [thread](https://github.com/nodejs/node-v0.x-archive/issues/3269).  As for what you say, artillery doesn't do a setup / teardown but it will reuse the connections.  Why do you think it will result in enobufs error frequently?  It happens whenver the loading reaches above 500 RPS.  I am using a virtual m/c with 8GB of RAM quad core.

**Comment by hassy** [comment]
Artillery creates a new connection for each virtual user so if your scenario only performs one request and you have a high arrival rate, it's possible that too many TCP connections are being created. That would be my guess. Try setting `config.http.pool` to something like 200 and see what happens.
