### ISSUE TITLE
support:  how does 'ensure' work?

### ISSUE THREAD

**Issue by urbaitel** [shoreditch-ops/artillery#139]
I can't find any documentation or anywhere online that explains how ensure works.

"ensure: cause Artillery to return with a non-zero error code under certain result conditions. Useful for CI"

Please explain!  Ideally I'd like to put some requirements in here to ensure performance driven development.

**Comment by hassy** [comment]
Once the test run is complete, the Artillery CLI looks at the value of `p50` / `p95` / `p99` for request latency, and exits with code 1 if it's bigger than what's specified in the `ensure` clause.

**Comment by urbaitel** [comment]
GREAT, thanks!

**Comment by urbaitel** [comment]
Can you explain p50, p95, p99 ..  is that the percentage (average) latency on 50%, 95% and 99% of the tests?

**Comment by urbaitel** [comment]
And how do I set that with ensure.  Example please?

```
ensure:
 p50: 500
 p95: 650
 p99: 700
```
??

**Comment by urbaitel** [comment]
OK, thanks for responding in the Gitter Channel.   Posting example here: https://github.com/shoreditch-ops/artillery-core/blob/966d84997c164c305f0ffd2833893c94fb7b7cf8/test/scripts/captures_regexp_group.json
