### ISSUE TITLE
WebSockets tests fail to run if using loop

### ISSUE THREAD

**Issue by alex7kir** [shoreditch-ops/artillery#141]
Steps to reproduce:
1) Create a websockets test with loop construct (example attached [test2.txt](https://github.com/shoreditch-ops/artillery/files/390266/test2.txt))
2) Run it

Actual result: test run fails with an error
Console output:

```
C:\Users\akir>artillery run C:\arttest\test2.json
Log file: artillery_report_20160729_124845.json
Phase 0 started - duration: 60s
 -C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\artillery-core\lib\engine_util.js:45
    newContext.vars.$loopCount = i;
                               ^

TypeError: Cannot set property '$loopCount' of undefined
    at aLoop (C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\artillery-core\lib\engine_util.js:45:32)
    at fn (C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:746:34)
    at C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:1213:16
    at C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:166:37
    at C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:706:43
    at C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:167:37
    at C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\async\lib\async.js:1209:30
    at WebSocket.<anonymous> (C:\Users\akir\AppData\Roaming\npm\node_modules\artillery\node_modules\artillery-core\lib\engine_ws.js:71:14)
    at emitNone (events.js:67:13)
    at WebSocket.emit (events.js:166:7)
```

**Comment by Elringus** [comment]
Well, that's sad: testing ws without variables and loop features is a pain :( Maybe put a warning to the docs, so people would be aware ws lacks some core features, before attempting to use the library...

**Comment by hassy** [comment]
Hey @Elringus. Yup, the WebSocket engine needs to catch up with the HTTP and Socket.io engines feature-wise. It shouldn't be too hard, most of the supporting code is reusable and just needs to be plugged into the WS engine. If you want to try giving it a go, I'd be very happy to help out - just open a work-in-progress PR!

**Comment by raghavendra-annakula** [comment]
As @Elringus said this library is not very useful for testing web socket traffic.  In web socket world we want to keep connection open for long time to test my application behaviour. Loops are ideal to test this. 

When can I expect a fix for this?

**Comment by hassy** [comment]
@raghavendra-annakula The fix will be available when someone sends a PR. Alternatively, if your company needs this feature asap, there's https://artillery.io/services-support.html

I agree that the WS engine needs to catch up, but the docs are very clear on what is supported - https://artillery.io/docs/testing_websockets.html

If you need to test long-lived connections, you can use long `think` periods in between messages.

**Comment by hassy** [comment]
@alex7kir @Elringus fixed in the upcoming `v1.5.0`

**Comment by raghavendra-annakula** [comment]
@hassy , 

I downloaded your trunk code , built the package. I am still observing same issue.

Ragavendra-MacBook-Pro:trunk ragavendra$ ./bin/artillery run wsclient.yaml 
Log file: artillery_report_20161201_180054.json

Phase 0 started - duration: 300s
 |[TypeError: Cannot set property '$loopCount' of undefined]


Ragavendra-MacBook-Pro:trunk ragavendra$ cat wsclient.yaml 
{
  "scenarios": [
    {
      "engine": "ws",
      "flow": [
        {
          "count": 100,
          "loop": [
            {
              "send": "hello world"
            },
            {
              "think": 1
            }
          ]
        }
      ]
    }
  ],
  "config": {
    "phases": [
      {
        "duration": 300,
        "arrivalCount": 3000
      }
    ],
    "ws": {
      "rejectUnauthorized": "false // Ignore SSL certificate errors - can be useful in *development* with self-signed certs"
    },
    "target": "ws://echo.websocket.org"
  }
}

**Comment by hassy** [comment]
@raghavendra-annakula are you using artillery-core from `master`?
