### ISSUE TITLE
HTTP: support capturing more than one value

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#147]
It should be possible to capture multiple values from a single response (of different types if needed, e.g. grab a header *and also* part of the JSON body).

To enable multiple captures, the `capture` attribute would be specified as an array of capture objects.

Related: https://github.com/shoreditch-ops/artillery/issues/96

**Comment by hassy** [comment]
Fixed in `v1.5.0-12`

https://github.com/shoreditch-ops/artillery/releases/tag/1.5.0-12

**Comment by vict01** [comment]
One example:       
       capture: 
            - jsonff: "data.pending"ff
              as: "pending"
            - json: "data.inQueue"
              as: "inQueue"
