### ISSUE TITLE
Socket.io support

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#15]
It would be nice to have first-class Socket.io support in Artillery.

(Closes https://github.com/shoreditch-ops/minigun/issues/9)

**Comment by ksplache** [comment]
Our team is also looking for socket.io support.  I'm up for adding it.  As far as I can tell, I should be adding it as a new engine in the artillery-core repo.  I'll fork that repo and give it a shot.

**Comment by hassy** [comment]
@ksplache Awesome! Copying and modifying the websocket engine would a good place to start. If you have any questions feel free to message me [on Gitter](https://gitter.im/shoreditch-ops/artillery) or drop me a line on github@veldstra.org

**Comment by ksplache** [comment]
@hassy It was not too bad to add the socket.io engine once I understood the artillery core framework a bit.  I submitted a pull request to the artillery-core repo.  I added unit tests & target servers for socket.io with http and with express.

**Comment by hassy** [comment]
@ksplache Great! :) I presume this does everything you need to test your app?

I've published `v1.5.0-0` - https://github.com/shoreditch-ops/artillery/releases/tag/1.5.0-0
