### ISSUE TITLE
-k/--insecure flag not respected by the WS engine

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#150]
https://github.com/shoreditch-ops/artillery/issues/59#issuecomment-237179260

**Comment by alex7kir** [comment]
Could you pleae tell when you are going to fix it? At least approximately.

**Comment by hassy** [comment]
Fixed in `v1.5.0-12`

https://github.com/shoreditch-ops/artillery/releases/tag/1.5.0-12
