### ISSUE TITLE
Ramp Phase 0 => N Should be Valid

### ISSUE THREAD

**Issue by erikerikson** [shoreditch-ops/artillery#151]
Expected: A properly formed ramp phase from 0 to N should ramp from no load to N RPS by the end of the phase's duration.

Observed: a ramp phase that starts at zero is treated as a pause phase, no matter how high it is specified to ramp.

```
{
    "config": {
        "phases": [
            {
                "duration": 100,
                "arrivalRate": 0,
                "rampTo": 50
            }
        ]
    },
    "scenarios": [
        {
            "flow": [
                {
                    "get": {
                        "url": "http://www.google.com"
                    }
                }
            ]
        }
    ]
}

```

A temporary workaround is to change the zero to a one.

**Comment by hassy** [comment]
Thanks @erikerikson. This is a quirk of how ramps are currently implemented (not very well tbh) - new implementation incoming!

By the way (it's not documented anywhere at the moment), the way ramps are meant to work is as a shortcut to manually writing out a sequence of normal `arrivalRate` phases. To use the example above, the ramp definition is meant to be transformed behind the scenes to:

```javascript
[
  { arrivalRate: 0, duration: 1.96 },
  { arrivalRate: 1, duration: 1.96 },
  { arrivalRate: 3, duration: 1.96 }
  // ... etc
  { arrivalRate: 50, duration: 2 }
]
```

Does that match your intuition of what ramps do?

**Comment by erikerikson** [comment]
Seriously no problem.  I ran into this and had to be less exact in my script-splitting code as a result.

My use case is that I was decomposing something (roughly) like
`[{ arrivalRate: 1, rampTo: 100, duration: 100 }]`
where each lambda is soft-limited to 50 RPS so that becomes
`[{ arrivalRate: 1, rampTo: 50, duration: 50 }, { arrivalRate: 50, duration: 50 }]`
and
`[{ pause: 50 }, { arrivalRate: 0, rampTo: 50, duration: 50 }]`
where the first is executed in one lambda and the second in another.

I simply hard coded starting at 1 instead of 0.

**Comment by erikerikson** [comment]
As far as my intuition about the behavior of ramps, I'm not quite sure.

I think that your example is pretty much my raw expectation.  This is probably a best first implementation of ramps.

That said, what I've been seeing is that the ramp has largely been a step function where sometimes it produces the level you would expect from your arrivalRate decomposition except semi-regularly it produced one less:
![image](https://cloud.githubusercontent.com/assets/571200/17574675/1c1d9d38-5f18-11e6-9c4b-97eb43df6880.png)

Note that the traffic bounces between 0 and 1 before bouncing between 1 and 2.  Importantly it does that relatively uniformly.

In that mental context/framing I was thinking that I would expect that the arrival rate would be the base arrival rate (i.e. 1) and then as one approached the next step that an extra request would become more probable.  That way, a ramp from 1 to 2 would start out producing 1 RPS.  Half way through I would expect to get 1 RPS 50% of the time and 2 RPS 50% of the time.  As the end was approached, I'd expect to see 2 RPS pretty much 100% of the time.  Doing some nearest-neighbor averaging I would then expect the graph to be more or less a straight line from 1 to 2.

**Comment by erikerikson** [comment]
maybe that arrival rate of 0 would turn into a pause.  :)

**Comment by hassy** [comment]
Ramps starting at 0 are supported now.

> In that mental context/framing I was thinking that I would expect that the arrival rate would be the base arrival rate (i.e. 1) and then as one approached the next step that an extra request would become more probable. That way, a ramp from 1 to 2 would start out producing 1 RPS. Half way through I would expect to get 1 RPS 50% of the time and 2 RPS 50% of the time.

Yes ramps could be implemented this way, but with users rather than requests. The relationship between active users and RPS is not linear - it can be, but it's not a given. Ramps increase the number of arrivals over time, how that translates to RPS depends on how many requests there are in a scenario, response time of different requests in a scenario etc.
