### ISSUE TITLE
Ramp Phase should respect Duration

### ISSUE THREAD

**Issue by erikerikson** [shoreditch-ops/artillery#153]
Expected: a ramp phase should run for it's duration and no more (or less) (within reason)

Observations:
```
H = hour, M = minute, S = second
SSS duration ramp SS => SSS ran from HH:MM:SS to HH:MM:SS = M:SS

240 duration ramp  1 =>  50 ran from 10:42:26 to 10:46:36 = 4:10
240 duration ramp  1 => 100 ran from 11:04:56 to 11:09:01 = 4:05
240 duration ramp 50 => 100 ran from 11:10:43 to 11:14:46 = 4:03
120 duration ramp  1 =>  50 ran from 11:15:57 to 11:18:02 = 2:03
120 duration ramp  1 => 100 ran from 11:20:14 to 11:22:16 = 2:02
120 duration ramp 50 => 100 ran from 11:23:22 to 11:25:23 = 2:01
120 duration ramp 50 =>  55 ran from 11:28:13 to 11:30:14 = 2:01
120 duration ramp  1 =>   5 ran from 11:31:41 to 11:34:05 = 2:44
120 duration ramp  1 =>   5 ran from 11:41:14 to 11:43:37 = 2:23
120 duration ramp  1 =>   5 ran from 11:46:03 to 11:48:25 = 2:22
120 duration ramp  1 =>   2 ran from 11:37:15 to 11:39:56 = 2:41
120 duration ramp  1 =>   2 ran from 12:01:46 to 12:04:27 = 2:41
120 duration ramp  1 =>   2 ran from 12:07:27 to 12:10:07 = 2:40
```

**Comment by erikerikson** [comment]
When I run some of these on a beefier machine, while still a small sample size, I get very reliable values:
```
120 second ramp 1 => 2 ran from 12:28:44 to 12:31:24 = 2:40
120 second ramp 1 => 2 ran from 12:33:31 to 12:36:11 = 2:40
120 second ramp 1 => 2 ran from 12:37:08 to 12:39:48 = 2:40
```

**Comment by hassy** [comment]
Interesting! Do you have a reproducible test case to demonstrate @erikerikson? We are talking purely about the length of time in which arrival events are generated here right? (and not the total duration of time it takes for users launched in a phase to finish their scenarios)

**Comment by erikerikson** [comment]
@hassy the data is not quite *that* clean.  It includes the flow executions but the flow for all of these is a single get with a latency that ranges from ~35ms not more than ~120ms.  I *am* making the assumption that the effect on the first result is relatively similar to the effect on the last result(s).

Script (slightly pared down):
```
{
    "config": {
        "phases": [
            {
                "duration": 120,
                "arrivalRate": 1,
                "rampTo": 2
            }
        ]
    },
    "scenarios": [
        {
            "flow": [
                {
                    "get": {
                        "url": "http://www.google.com"
                    }
                }
            ]
        }
    ]
}
```

Running that script, I saw:
`120 second ramp 1 => 2 ran from 12:55:17 to 12:57:57 = 2:40`

If you could try reproducing this, I'd appreciate knowing that I'm not adding something stupid.

**Comment by hassy** [comment]
@erikerikson the code running ramps was doing too much work under some conditions, new implementation incoming

**Comment by erikerikson** [comment]
Awesome!  Thank you @hassy

**Comment by erikerikson** [comment]
FWIW...  The reason this is relevant is that we're splitting load across Lambdas and any overrun creates an overlap that creates a period of double the intended load.  We'll be working to open source that splitting implementation soon.  Auto-dropping 15K RPS feels nice.

**Comment by hassy** [comment]
@erikerikson cool, looking forward to playing with it!

**Comment by RobGruhl** [comment]
![screen shot 2016-08-09 at 1 03 27 pm](https://cloud.githubusercontent.com/assets/13952844/17561469/fa59da64-5eda-11e6-9627-19dc3430828d.png)

Example ramp with over-run issues.

**Comment by hassy** [comment]
Fixed in https://github.com/shoreditch-ops/artillery-core/pull/89
