### ISSUE TITLE
Support for Multipart File Upload Requests

### ISSUE THREAD

**Issue by code-4-fun** [shoreditch-ops/artillery#155]
Today I just stumbled upon this framework and would like to give it a spin. However, I would like to check if there is support for multi-part file upload requests. Apologies, I did not read the documentation in complete detail, but would like to know if its there...

**Comment by hassy** [comment]
No, file uploads aren't well supported right now.

There's an existing issue here already - https://github.com/shoreditch-ops/artillery/issues/106
