### ISSUE TITLE
Install successful but no dinosaur for me

### ISSUE THREAD

**Issue by wjgilmore** [shoreditch-ops/artillery#159]
Hi,

Per https://artillery.io/docs/gettingstarted.html I installed Artillery like so: `npm install -g artillery`. No installation errors were reported, but I didn't see a dinosaur as the docs indicated. I confirmed Artillery is in fact installed by running:

    $ artillery --version
    1.5.0-12 

No big deal obviously but wanted to let the team know so the docs could be updated if this is no longer a "feature". :-)

Jason

**Comment by wjgilmore** [comment]
Aaaaaaaannd I am an idiot. Spelled dino as "dyno".

**Comment by hassy** [comment]
No worries @wjgilmore :)
