### ISSUE TITLE
Run flow elements in parallel

### ISSUE THREAD

**Issue by jmredfern** [shoreditch-ops/artillery#164]
To simulate browser calls which happen in parallel:

```
    "scenarios": [
        {
            "flow": [
                [
                    {
                        "get": {
                            "url": "/rest/events",
                        }
                    },
                    {
                        "get": {
                            "url": "/rest/stream",
                        }
                    }
                ]
            ]
        }
    ]
```

**Comment by hassy** [comment]
Could you explain the use case a little bit more @jmredfern? If you could mark a request as async (e.g. with something `async: true`) to make Artillery not wait for a response, would that do what you need it to do?

**Comment by hassy** [comment]
Closing as there are no plans to implement this for now - can be re-visited and re-opened again later.

**Comment by clarkie** [comment]
I have a use case for this. We have a route that returns configuration for a home page which in turn gives the client a number of sources to go and get further data from. The second set of requests would be called in parallel by a normal browser. 

For example the response from the first request could be something like this: 
```
[
  {
    "source": "/curations/94afe353-8b89-4085-8c06-a10cde5f70e5/products",
    "title": "Collections",
  },
  {
    "source": "/curations/4e19b3fd-1ea8-455b-b7b4-83abd64a1884/products",
    "title": "Popular this week",
  },
  {
    "source": "/curations/ec2019d9-d2a0-4e7e-88b8-93f19b868e1b/products",
    "title": "New and noteworthy",
  }
]
```
we'd then want to call each source url in parallel.

What do you reckon?

**Comment by hassy** [comment]
I see what you're trying to do. That would also require a mechanism to dynamically set up new requests in the running scenario - there isn't a way to do it at the moment.

One way to achieve what you're trying to do is a hook function, which can be as simple as `Promise.all()`ing a bunch of requests.

**Comment by clarkie** [comment]
Ah, yeah, I don't mind hardcoding the response's urls but yeah, that should work for me. I'll report back once I've tried it

Thanks
