### ISSUE TITLE
[Feature Request] Validate parts of a socket.io message

### ISSUE THREAD

**Issue by gboysko** [shoreditch-ops/artillery#171]
I like that I can verify a response message of a certain type ("channel") arrives in my flow, but how can I verify that a specific field is present?

In particular, the nature of my response messages is that they will contain some dynamically generated data and what I really want to do is check whether a specific field (e.g., `status`) has a boolean of `true`. 

I can imagine that we can use the same `json` keyword to locate a specific field in the response message and compare it with a static value or placeholder.

**Comment by gboysko** [comment]
Implemented as part of [PR 104](https://github.com/shoreditch-ops/artillery-core/pull/104) in artillery-core.

**Comment by hassy** [comment]
PR merged, closing this.
