### ISSUE TITLE
Artillery should halt testing if any specified plugin cannot be loaded

### ISSUE THREAD

**Issue by gwsii** [shoreditch-ops/artillery#183]
When a plug-in code throws an error, Artillery reports the name of the plug-in as 'unable to load' and continues with the test. This is a problem for a couple of reasons:

1) Assuming the user needed that plug-in to perform testing, attempting to continue is over-optimistic. Artillery should exit at that point and refuse to test.

2) Artillery currently does not show any information about how or why the plug-in could not be loaded, at a minimum if an exception was thrown that message and stack should be reported.

**Comment by hassy** [comment]
Yes 👍

**Comment by gwsii** [comment]
Actually, it makes much more sense to log this against artillery-core. Closing this bug and opening one on that repo.
