### ISSUE TITLE
beforeRequest doesn't appear to accept changes to the .url property

### ISSUE THREAD

**Issue by duncanmeech** [shoreditch-ops/artillery#185]
The URI's I'm hitting need to be programmatically set. I can set the requestParams.json in the beforeRequests hook but changing the .url property doesn't appear to have any effect.
Tried poking through the source but artillery-core is MIA from the repo.
( actually this appears to be caused a little asymmetry...the url is usually relative to the target
but if you modify you must supply the full path ).

**Comment by hassy** [comment]
The `uri` property is the one to change. (This should be documented.)

Core is in a separate repo: https://github.com/shoreditch-ops/artillery-core/

**Comment by joelchen** [comment]
@hassy Looking forward to more documentation for (requestParams, context, ee, next).

**Comment by hassy** [comment]
@joelchen Have you seen this: https://artillery.io/docs/testing_http.html#advanced-writing-custom-logic-in-javascript - Any suggestions on what to improve or add specifically?

**Comment by keyscores** [comment]
@hassy can we get some more clarity on using Request in requestParams. 
I'm familiar with Request, but setting a json body doesn't seem to be used in the request.
```
function setJSONBody(requestParams, context, ee, next) {
  requestParams = {
    json: { key: 'value' },
    qs: { a: 1 }
  }
  return next(); // MUST be called for the scenario to continue
}
```
I'm not seeing it in the target URL logs.

Could you add an example in the docs?
Thanks in advance

**Comment by hassy** [comment]
@keyscores looks like you're replacing the entirety of request parameters, including the URL. The request won't be made so you won't see it in the logs

**Comment by rdok** [comment]
As per  hassy's comment at  https://github.com/shoreditch-ops/artillery/issues/185#issuecomment-250117197 
```
module.exports = {prepareEnvs: prepareEnvs};
require('dotenv').config();

function prepareEnvs(requestParams, context, ee, next) {

    requestParams.uri = process.env.APP_URL;

    return next();
}
```
