### ISSUE TITLE
How values are picked from CSV

### ISSUE THREAD

**Issue by danielo515** [shoreditch-ops/artillery#188]
Hello,

My doubt consist in two parts:
1. Can I specify more than one CSV file as payload?
2. If the answer is no, how are the values picked?

In case you only specify one file, documentation says that values are randomly picked, but it does not specifies how. Is a random row picked and then all the values from that row used? Or every time a new random value is picked?
This is important because if all the values of a single row are used each time, I have to generate a CSV with all the possible combinations for a real random behavior.

Thanks

**Comment by hassy** [comment]
Yep, you can specify multiple payloads: https://artillery.io/docs/script_reference.html#payloads

A row is picked at random for each virtual user and the values are used to populate the variables.

**Comment by danielo515** [comment]
If I specify several payload files, how does artillery know where to find the required variables? I want to have several files for different variables.

**Comment by hassy** [comment]
The variables are set by the `fields` property on a payload object.

**Comment by danielo515** [comment]
Yes, you have to specify the fields, but since you specify payloads and fields separately, how do you relate the correct fields to the correct file?

**Comment by hassy** [comment]
Each payload object in the config has its own field attribute (so you don't
specify the payload on the command line but in the script itself)

**Comment by danielo515** [comment]
Sorry @hassy but I'm still not understand how do you can specify multiple payloads. I re-read the examples and there is no example about how specifying several payload files... Ok, I just saw the sentence 'it can be an array'. I missed that. Maybe you could make it more prominent with an example? Thanks anyway.

**Comment by hassy** [comment]
Thanks for the feedback, very valuable for making the docs better!

**Comment by oscarmullin** [comment]
Hi, this link is broken https://artillery.io/docs/script_reference.html#payloads

Thanks
