### ISSUE TITLE
Artillery hangs under Node 7

### ISSUE THREAD

**Issue by duncanjbrown** [shoreditch-ops/artillery#204]
Running under node 7.x causes the artillery process to hang at 100% CPU after a few seconds.

I created a repository with scripts to reproduce the issue using nodeenv here: https://github.com/duncanjbrown/node-artillery-bug-report

The process appears to be stuck in an infinite loop in Node's `timers.js`—debugger screenshot below. It never gets past line 572.

Artillery v1.5.0-17 will appear to continue working but no requests will be sent or responses received.
Artillery v1.5.0-16 will freeze outright.

I am running OS X 10.11.6.

![screen shot 2016-11-10 at 17 47 59](https://cloud.githubusercontent.com/assets/642279/20187846/e9cb4116-a76d-11e6-907b-d4a6ef5f66a7.png)

**Comment by hassy** [comment]
Thanks @duncanjbrown, great bug report. 💚

**Comment by hassy** [comment]
Spent some time investigating this bug. It only manifests under Node 7 and **not** Node 4 or 6.

The implementation of `rampTo` (https://github.com/shoreditch-ops/artillery-core/blob/master/lib/phases.js#L84-L123) is the place to look further. Phaser's unit tests pass on 4 & 6 but fail on 7, which can be confirmed by running them under respective Node versions with:

```sh
DEBUG=test:phases,phases node test/unit/phases.test.js
```

Current hypothesis is that Nanotimer is broken under Node 7 but that still needs to be confirmed.

**Comment by hassy** [comment]
The issue is in Node itself, affected versions are v6.8.1 and above.

Issue: https://github.com/nodejs/node/issues/9756

**Comment by hassy** [comment]
Thanks for the great bug report @duncanjbrown - made finding the issue much easier.
