### ISSUE TITLE
Concurrent users calculation may be incorrect

### ISSUE THREAD

**Issue by jasondbaker** [shoreditch-ops/artillery#206]
I recently ran a test against a script that is designed to simulate long latency requests. The test has one phase with a duration of 300s and an arrivalCount of 5. The test runs for 610s and it initiates 5 requests to a script which responds to each request after 300s. 

After running the test, the concurrent users chart reports that at one point in the test there were 50 concurrent users. This value seems incorrect by a factor of 10. 

I've attached the report file to this issue. Here is the test configuration:

{
	"config": {
		"target": "<removed>",
		"phases": [{
			"duration": 300,
			"arrivalCount": 5
		}],
		"timeout": 1000
	},
	"scenarios": [{
		"name": "test 300sec responses for 300 secs",
		"flow": [{
			"get": {
				"url": "/perf.php?__ms=300000"
			}
		}]
	}]
}

[report.zip](https://github.com/shoreditch-ops/artillery/files/593259/report.zip)

**Comment by hassy** [comment]
Ooh, definitely looks like a bug. Thanks @jasondbaker
