### ISSUE TITLE
Feature: loop until a condition is met

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#207]
It can be useful to loop until a condition is met.

This could be done with something like a `whileTrue` hook, which would call back with `true` or `false` to indicate whether the loop should continue and would have access to the full `context`.

**Comment by joesb** [comment]
Something like this would be great. Added a comment in #308 to describe my scenario. 

For me, support for an equivalent of `beforeRequest` or `beforeScenario` for loops, with arguments to alter the loop specs, would be great.

**Comment by hassy** [comment]
Thanks for the info @joesb. Always helpful to have some real use cases in mind when adding a feature!

**Comment by Cristy94** [comment]
Let's say you have a chat room which is full and players sometimes leave the room. You might want to loop sending a join-room event until you can finally join.

**Comment by psychowico** [comment]
:+1: It would be useful.
In my case I upload a file that is queued to process by another service.
Then I asking for file status. Response status code `202 ACCEPTED` means that output is still not ready. When I got status code 200 I can continue scenario.

**Comment by jordan-brough** [comment]
Our case is that we'd like to make a first request that returns an array of URLs (assets for a product, length varies by product) and then we want to request each of those URLs.  If there is a better way please let us know, but it seems like "loop with a condition" could allow us to do that.

**Comment by hassy** [comment]
Now available in Artillery 1.6.0-9.

Docs: https://artillery.io/docs/http-reference/#experimental-looping-with-custom-logic

**Comment by Cristy94** [comment]
What about the WS engine?
