### ISSUE TITLE
Warn when rampTo is used with Node.js >= 6.8.1 and < 7.3.0

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#210]
Artillery may hang if an arrival phase uses `rampTo` under Node 6.8.1 or above:

Details: https://github.com/shoreditch-ops/artillery/issues/204

We need to print a warning when `rampTo` is used under an affected version of Node.

**Comment by opatut** [comment]
I am using 7.3.0 and have not run into any problems. [Apparently, the fix has been released](http://nodesource.com/blog/node-js-7-3-0-release-brief/ (search for **\#9759** in there).

So can we remove the warning for those node versions again?

**Comment by hassy** [comment]
@opatut Yup, thanks!
