### ISSUE TITLE
[Feature Request] - Allow for specifying Username/Password to generate Authentication Header

### ISSUE THREAD

**Issue by renaudholcombe** [shoreditch-ops/artillery#211]
It would be useful (unless it's already a feature, but if so, I can't find it) to be able to generate an authentication http header from a username and password. Currently it seems like one needs the already generated header in order to pass authorization information.

**Comment by hassy** [comment]
HTTP Basic Auth is supported (need to document it though) and can be used like this:

```javascript
{"get": {"url": "/protected", "auth": {"user": "hassy", "pass": "secret"}}}
```

**Comment by renaudholcombe** [comment]
Thanks for the response, but I believe I've tracked down a related bug; if one uses the sequence:
1. Perform post request and capture a json property.
2. Attempt to use that captured value in a subsequent request, the capture will not be transformed.

For instance, given: 
`              "get": { 
                "url": "/api/ibor/v2/PositionLots",
                "auth": 
                  { "user": "{{ capturedvalue }}", "pass": "blah"},
                "headers": {"test": "{{ glx2 }}"}
              }
`

You will see in the http request, the authorization header was generated using "{{ capturedvalue }}" as the user instead of the actual captured value. This issue does not occur for using the captured value within a header in the same request.

**Comment by hassy** [comment]
@renaudholcombe Yes, you're right - that was an oversight in the implementation. The fix is in and will be available in the next release of Artillery.
