### ISSUE TITLE
Is it possible to keep a constant concurrency rate through out the run?

### ISSUE THREAD

**Issue by soumsg** [shoreditch-ops/artillery#213]
When I set the arrivalRate to 10 and if the app server can process only 8 per sec, the next second concurrency level become 12. I was wondering if it is possible to keep a constant concurrency rate through out the run.

**Comment by hassy** [comment]
There's `arrivalCount` which can be used to create a specific number of virtual users, which will maintain a constant concurrency level if the scenarios are long.

Otherwise there's no way to maintain a constant concurrency rate.
