### ISSUE TITLE
Support nested loops

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#219]
It would be nice to be able to nest loops. To be able to nest loops, there will need to be a way to set the name of the counter variable (currently `$loopCount`).

**Comment by Marouane-BEN-ABBOU-Ayosaki** [comment]
how this works,how can i name the loopcounter in my yaml file?

**Comment by gaisihorfun** [comment]
@Marouane-BEN-ABBOU-Ayosaki did you manage to figure it out? Facing the same issue now

**Comment by Maru-Ben** [comment]
no i managed to use a index in my hook:
 ` - loop:
          - function: "setPdaIndex"
          - post:
              url: "/sap/pda"
              headers:
                x-api-key: "{{ x_api_key }}"
              json:
                pda_id: "PDALoadTest{{ $loopCount }}"
                station_id: "SSMA"
              capture:
                - json: "$.one_time_token"
                  as: pda_token
              expect:
                - statusCode: 201`

then in your hook.js you can use `function setPdaIndex(context, events, done) {
  context.vars['pdaIndex'] = context.vars['$loopCount'];
  return done();
}`
