### ISSUE TITLE
missing code in docs

### ISSUE THREAD

**Issue by SamDecrock** [shoreditch-ops/artillery#223]
Hi,

I was reading the docs saw that you forgot to add a reference to the csv file here: https://artillery.io/docs/testing_http.html#variables-from-a-file

No idea if it's intentionally or not. Just mentioning it here.

Keep up the good work, seems like a great improvement over JMeter!

**Comment by SamDecrock** [comment]
Nevermind, didn't read the part where you specify the csv file in the CLI :s

**Comment by hassy** [comment]
no worries :)
