### ISSUE TITLE
limit number of requests to 1

### ISSUE THREAD

**Issue by SamDecrock** [shoreditch-ops/artillery#224]
Hi,

Now a request is sent every second (specified in the docs).

I would like to use Artillery to test if a REST call succeeds, not to test if it survives multiple requests. Therefor I would to send one request per scenario.

Is that somehow possible?

Thanks,
Sam

**Comment by hassy** [comment]
Yes - specify a single scenario with one request and in your `phases` definition use an `arrivalCount` of 1.

Artillery does not send a request every second. It launches virtual users (the rate depends on what you specify in `phases`) which then run through one of the scenarios you define, which can consist of multiple requests.

If you're using `quick`, then use the `-c` option to create just one user.

**Comment by SamDecrock** [comment]
Thanks
