### ISSUE TITLE
Generate AWS headers using aws-sigv4 plugin

### ISSUE THREAD

**Issue by nishit-shah** [shoreditch-ops/artillery#228]
I have setup my aws account and have creds and region configured at ~/.aws/ path
my account is having region:us-east-1
Also configured the json file as displayed below for aws-sigv4 plugin:

  {

	"config": {
	"plugins": {
      "aws-sigv4": {

         "serviceName": "execute-api"
       }
   
    },
		"target": "https://hosttest.amazonaws.com",
		"phases": [
			{
				"duration": 60,
				"arrivalRate": 20
			}
		],
		"defaults": {
			"headers": {
				
				
			}
		}
	},
	"scenarios": [
		{
			"beforeRequest": "addAmazonSignatureV4",
			
			"flow": [
				{
					"get": 
					{
					    "url": "/testapi"
					}
				}
			]
		}
	]
}

When sent the request with following command:
artillery run test.json
Got error saying:
Type error: Not a string or buffer

Note:Also updated node from 4.4.5 to 7.x stable version but still getting the same error.

**Comment by hassy** [comment]
You'll have a better chance of getting an answer if you move the issue to plugin's repo:

https://github.com/Nordstrom/artillery-plugin-aws-sigv4

`artillery-plugin-aws-sigv4` is not part of Artillery itself.

**Comment by nishit-shah** [comment]
ok :)
