### ISSUE TITLE
Variables in capture statements

### ISSUE THREAD

**Issue by astanciu** [shoreditch-ops/artillery#230]
It would be super useful to have variable evaluation inside capture statements. Ex:
```
"capture": {
  "json": "$.data.tickets[?(@.request.uuid == '{{ req_id }}')].uuid",
  "as": "uuid"
}
```

Example usecase Flow: 
1. do a POST to create a new User
2. capture the generated users' id
3. do a GET /users  (specifically want this, not /users/{id})
4. capture something from the results (finding the newly generated user by ID)
5. do something else with that data

**Comment by hassy** [comment]
Good idea 👍

**Comment by astanciu** [comment]
Can we get this patch included when doing `npm install artillery` ?
