### ISSUE TITLE
error: unknown option `-n'

### ISSUE THREAD

**Issue by oscarvesga** [shoreditch-ops/artillery#244]
Hi, I am using the nex command line and I get this error.

`artillery quick --duration 60 --rate 10 --num 20 http://registro.uniandes.edu.co`

**Comment by hassy** [comment]
@oscarvesga What version of Artillery is that? (`artillery -V`) Does `-n` instead of `--num` work?

**Comment by oscarvesga** [comment]
`artillery -V` 
`1.4.1`

**Comment by hassy** [comment]
You need `v1.5`

**Comment by oscarvesga** [comment]
How can I get the last version using `npm install -g artillery` ?

**Comment by hassy** [comment]
@oscarvesga `npm install -g artillery@latest` should do it
