### ISSUE TITLE
External processor script not running, but no errors.

### ISSUE THREAD

**Issue by tetreault** [shoreditch-ops/artillery#246]
Hello, 

I'm trying to use Artillery to test out socket.io on a project. I want to emulate two socketio events I have - `mouse_position` and `mouse_draw`. Artillery is correctly hitting my site, however the data being sent to it is empty which is how I know the processor script isn't running. 

Here is `socket-stress-test.json`:
```
{
  "config": {
    "target": "http://fakesitename.com",
    "phases": [
      {
        "duration": 200,
        "arrivalRate": 10,
        "name": "Warm-up"
      }
    ],
    "processor": "functions.js"
  },
  "scenarios": [
    {
      "name": "A user moving the mouse",
      "engine": "socketio",
      "flow": [
        {
          "emit": {
            "function": "setSocketData",
            "channel": "mouse_position",
            "data": {
              "uuid": "{{ uuid }}", 
              "icon": "{{ icon }}", 
              "x": "{{ x }}",
              "y": "{{ y }}" 
            },
            "response": {
              "function": "setSocketData",
              "channel": "mouse_draw",
              "data": {
                "uuid": "{{ uuid }}", 
                "icon": "{{ icon }}", 
                "x": "{{ x }}",
                "y": "{{ y }}"
              } 
            }
          }
        }
      ]
    }
  ]
}
```

Here's the small `functions.js` file: 
```
'use strict';

// Import the same functions we utilize in server.js
const randomEmojiPNG = require('../helper/helper').getRandomEmojiPNG;
const uuid = require('node-uuid');

const setSocketData = (context,events,done) => {
  context.vars.uuid = uuid.v1();
  context.vars.icon = randomEmojiPNG();
  context.vars.x = Math.floor(Math.random() * 1000);
  context.vars.y = Math.floor(Math.random() * 1000);
  return done();
};

module.exports = { setSocketData: setSocketData };
```

I've followed [this](https://github.com/hassy/socketio-load-test-artillery-example) pretty closely by @hassy , so I'm at a loss why mine just isn't working. Any help would be greatly appreciated. 

When I see incoming connections coming into my site it just appears like this:
![mouse_draw](https://cloud.githubusercontent.com/assets/5934354/22127524/3497a40e-de6a-11e6-9e35-779803895cc9.jpg). 

Misc Info: 
Node - v6.9.5
NPM - v4.1.1
Artillery - v1.5.0-22

**Comment by hassy** [comment]
`function` is a top level "action", whereas in your script it's an attribute of the `emit` action. It needs to be its own step before `emit`.

**Comment by tetreault** [comment]
OMG... If I could faceplam harder I would! How was I not noticing that... Thanks man!

**Comment by tetreault** [comment]
@hassy I moved `"function": "setSocketData"` above the `emit`. It still is not populating any of the variables though. Based on the above I provided, is there anything else you think I should look at?

Thanks again for the help btw.

**Comment by tetreault** [comment]
This works perfectly now and can be closed!
