### ISSUE TITLE
Feature: Call Custom Javascript Functions on start and end of the overall run

### ISSUE THREAD

**Issue by tslape** [shoreditch-ops/artillery#248]
It would be useful to be able to call a custom Javascript Functions before any tests have run and once all tests have been completed. 

The use case is using custom reporting and using it to clear out all old files before starting a new run. 

Could also be useful if running Artillery on a server and being able to send a notification once the run has finished.

**Comment by hassy** [comment]
There's already an issue to track this in #131. Closing this.

**Comment by tslape** [comment]
Did not see that one. Thank you!
