### ISSUE TITLE
Trying to get JSON into socket.io script

### ISSUE THREAD

**Issue by gboysko** [shoreditch-ops/artillery#251]
I'm using Artillery to invoke a socket.io server. In the past, the calls to `emit` were made using simple objects: scalar valued fields. I need something more sophisticated where a field is itself a JSON object which comes from the CSV file.

I understand that everything that comes back from the CSV parser is strings. We can consider either a "smart" analysis (e.g., the first and last characters of the string are `{` and `}`) or we can use a type prefix in the CSV (e.g., "...","json:{\"someField\": 123}","...").

The problem seems to be our use of Hogan templates. Everything coming back from the template is a string, correct?

**Comment by gboysko** [comment]
FWIW, I would be more than willing to implement this feature if the community feels it adds value. If so, I just need some indication of the best way to proceed. My approach would be to introduce some optional type qualifier in CSV fields which instruct Artillery in how to convert the string value to the ultimate value. This seems easy enough.

The bigger challenge (as far as I can tell) is getting Hogan to use this information when processing the template.

Am I on the right track?

**Comment by hassy** [comment]
Types are preserved properly in templates now, and values loaded from CSVs get cast to native types automatically too, closing the issue. :)
