### ISSUE TITLE
Git Version Numbers?

### ISSUE THREAD

**Issue by gboysko** [shoreditch-ops/artillery#253]
Shouldn't we increment the patch version every time there is a release? There are 22 releases on 1.5.0 and wouldn't be consistent with semver best practices to increment the patch number each time?

**Comment by hassy** [comment]
Those were all [pre-releases](http://semver.org/#spec-item-9) which are part of the semver spec. There's only one v1.5.0 and `npm install artillery` will install 1.5.0 rather than any of the pre-releases.

**Comment by gboysko** [comment]
Thanks for the reply. Sorry for the confusion, I guess I haven't worked with an NPM module that utilized pre-releases.

So, 1.5.0 hasn't released yet? It doesn't show up under the *Releases* tab. However, after running `npm install artillery`, `artillery --version` shows `1.5.0`. 

I was just trying to answer the question (to a colleague), do you know if you have the pre-release with our changes (1.5.0-17)?

**Comment by hassy** [comment]
Yes, 1.5.0 is out but we're behind on writing up proper release notes for
it. :-)

**Comment by gboysko** [comment]
I see. That explains it. Thanks for the clarification.
