### ISSUE TITLE
security advisories

### ISSUE THREAD

**Issue by bonesoul** [shoreditch-ops/artillery#256]
![untitled](https://cloud.githubusercontent.com/assets/73215/22858912/83869b5c-f0d4-11e6-90d0-c678cd1f98f3.png)

**Comment by hassy** [comment]
Thanks. Will gladly merge a PR fixing those although none apart from maybe the first one are relevant to Artillery as a CLI app that does not run as a server exposed to the internet. :)

**Comment by hassy** [comment]
Fixed in `1.5.8-2`
