### ISSUE TITLE
TCP test support

### ISSUE THREAD

**Issue by ogrodnek** [shoreditch-ops/artillery#263]
Hi!

I was wondering if anyone has thought about adding some simple TCP testing support, or how difficult it would be to plug in another engine into the framework?

My use case is I'm trying to test out the performance of some different graphite backends.  The [graphite protocol is a pretty simple plaintext one](http://graphite.readthedocs.io/en/latest/feeding-carbon.html).

thanks!

**Comment by hassy** [comment]
It should be fairly straightforward to plug another engine in (Artillery is designed to allow for that) and I know that Artillery users have created their own custom engines. The easiest route is probably to use a Graphite module from `npm` to implement a graphite engine.

**Comment by hassy** [comment]
Closing for now.
