### ISSUE TITLE
Run artillery within an express server loops infinite

### ISSUE THREAD

**Issue by cesarZubillaga** [shoreditch-ops/artillery#264]
Hi!

After artillery printing "all scenarios completed" i get infinite:
```
Report for the previous 10s @ 2017-02-27T09:43:03.046Z
  Scenarios launched:  0
  Scenarios completed: 0
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
```
This is my enviroment:

artillery -V 1.5.1
node -v v6.8.0
express  -v 4.14.1

I have created a repository so you can reproduce the error.

https://github.com/cesarZubillaga/artilleryexpresstesting

I have tested this with LTS node version 6.10.0 and last node 7.6.0 resulting in the same error.

Thanks

**Comment by hassy** [comment]
Thanks for the bug report @cesarZubillaga

**Comment by cesarZubillaga** [comment]
To make my code run inside the server i did some changes and now i am running artillery as a command. I needed to capture the output and send to the client. This is how i solved it.

BTW thanks for this cool tool.

```
var exec = require('child_process').exec;
var command = 'artillery run test.yml';
var child = exec(command);
child.stdout.on('data', function(data) {
      //do what you want with the data output of the command
});
