### ISSUE TITLE
Docs unclear

### ISSUE THREAD

**Issue by KidkArolis** [shoreditch-ops/artillery#267]
Hi,

maybe it's just me, but after a few hours of using the tool (which is great btw), I'm still a little confused on what the options mean. In particular, I'm confused about the mismatch between cli options and yml options, e.g. 

```
artillery quick --duration 60 --rate 10 -n 20 http://my.app.dev/api/resource
```

Is explained as "To create 10 virtual users every second for 60 seconds which will send 20 GET requests each".

But when reading `phases` docs, I only see these options: `arrivalRate`, `rampTo`, `arrivalCount and `pause`. Which one of those maps to `n` in the above (as I understand neither, how do I make each user make 20 requests then?). Also what's the difference between `arrivalCount` and `arrivalRate` and how does that map to that cli example?

Perhaps a few more fleshed out examples could help. For example, that same CLI example "To create 10 virtual users every second for 60 seconds which will send 20 GET requests each" - how do you replicate that in yml?

How do I use artillery to keep ramping up until server/artillery crashes?

Sorry if this issue seems all over the place, just wanted to discuss how the docs could be improved (or perhaps it's just me...).

**Comment by KidkArolis** [comment]
What's the difference between "RPS Count" vs "Mean RPS"?

**Comment by KidkArolis** [comment]
I think I'm starting to get it.. arrivalRate is arrivalRate – how many users are added each second, and if the scenario has a flow with say 5 requests, each of those users will perform those 5 requests.

I'll close this issue, but still have some questions in case you have time to respond:

1. What's the difference between rps count and mean rps?
2. To control how many requests each user makes in the yml config, is the only way to copy paste the same request multiple times in the flow?

**Comment by hassy** [comment]
hi @KidkArolis 

1. RPS count is the total number of requests made in a period. Mean RPS is the average number of requests per second during that period.
2. Check out the `loop` command: https://artillery.io/docs/testing_http.html#loop-through-a-number-of-requests

`arrivalRate` is indeed the number of users "added" every second (ie arriving to use the application) - that's what `--rate` corresponds to.

**Comment by xuan9230** [comment]
I'd like to add a bit to @hassy 's answer:
If you are viewing the report graph generated by artillery, RPS Count normally means the count of requests finished in last 10 secs.

I find it a little confusing too - it's a period but PS seems indicates 'per second'.

**Comment by Pris17** [comment]
How does arrivalRate and arrivalCount work?
