### ISSUE TITLE
Iterate through a list of json files

### ISSUE THREAD

**Issue by jetheurer** [shoreditch-ops/artillery#268]
I'd like to be able to point my config to a directory that contains a bunch of json files I'd like to loop through.  My payloads are complex and nested and I'd like to have each issued multiple times.

Is this possible?

**Comment by hassy** [comment]
Not sure what you mean @jetheurer, can you give an example?

**Comment by jetheurer** [comment]
Sorry @hassy I think I can do what I want with `beforeRequest`

**Comment by hassy** [comment]
Great, no worries @jetheurer :)
