### ISSUE TITLE
Injecting random/generated parameters to a request

### ISSUE THREAD

**Issue by glock18** [shoreditch-ops/artillery#275]
Hey!

It seems to be impossible to generate a pseudorandom string on a per-request basis for socketio engine right now. Even some basic increment for test purposes would be fine, but preferably I'd like it to be a function returning generated string.

In my test I'd like to generate a random string for every client without having to manually type them into a csv or inline array. In case of http engine it is doable via beforeRequest hook, it doesn't get invoked by socketio engine unfortunately. Is there anything that I'm missing here?

**Comment by hassy** [comment]
We need to add support for hooks in the socket.io engine. Related: #170

**Comment by hassy** [comment]
This is possible with a `function` step, closing. :)
