### ISSUE TITLE
Any particular reason to limiting input formats to json and yml (not allowing javascript)

### ISSUE THREAD

**Issue by glock18** [shoreditch-ops/artillery#276]
Hey!

Is there any reason behind using purely non-script input formats? I feel it wasn't done without a good reason, as having an ability to use sync functions as any parameter in config, would yield great customization capabilities, with seemingly little drawback. I must be missing something here?

Inspired by https://github.com/shoreditch-ops/artillery/issues/275

I appreciate any explanation really, or thoughts on whether it would've been a sound or terrible idea to add .js support at all.

Thank you in advance!

**Comment by hassy** [comment]
Hook functions provide the ability to customize scenarios already.

Allowing for test scripts to be JS is not a terrible idea, but the end result would look very similar to how a YAML test looks like already - you'd be mostly making calls to exposed Artillery APIs. Not much benefit, but the ability to programmatically analyse and modify the test script would be gone (e.g. from a plugin).

**Comment by glock18** [comment]
I see, thank you for explanation @hassy

**Comment by hassy** [comment]
No worries. :)
