### ISSUE TITLE
How to handle single quotes in CSV file?

### ISSUE THREAD

**Issue by philjones88** [shoreditch-ops/artillery#278]
Take this scenario (excuse the pun)

Have a CSV that looks like:

```
1,bob,smith
2,andy,jones
3,andrew,o'neill
....
```

When I try and use these in a URL like:

```
"get": {
    "url": "/search?first={{ first }}&last={{ last }}&id={{ id }}"
}
```

I see this works fine for rows 1 and 2 but for row 3 I see in the apps logs:

`/search?first=andrew&last=o&`

It seems to be the single quote, but weirdly continues but doesn't put in the last entry either.

Any ideas?

`version = 1.5.0-20`
`node = 7.6.0`

**Comment by hassy** [comment]
Interesting, not sure if it's a bug in the CSV parsing library, Artillery itself, or if the single quote needs to be escaped, but should be easy enough to reproduce. Thanks for the bug report @philjones88

**Comment by gwsii** [comment]
@philjones88 Latest version now includes the ability to pass `options` in the [payload object](https://github.com/shoreditch-ops/artillery/blob/master/test/scripts/single_payload_options.json#L10), which will be passed to [csv-parse](http://csv.adaltas.com/parse/). Perhaps one of the csv-parse options will allow the proper parsing of your data.

**Comment by hassy** [comment]
Should be handled by quoting the offending field, which is supported by the CSV parsing library we use.
