### ISSUE TITLE
Can not report a statistical graph?

### ISSUE THREAD

**Issue by RifeWang** [shoreditch-ops/artillery#285]
I think artillery is very flexible, but it will be better if it can report a statistical graph.

**Comment by hassy** [comment]
Can you expand on that a little bit? What's a statistical graph? Got any examples?

**Comment by RifeWang** [comment]
@hassy I mean HTML file like apache ab.

**Comment by hassy** [comment]
there's `artillery report` command which takes a JSON file produced by `artillery run` and produces an HTML report.
