### ISSUE TITLE
Allow loop count to accept a variable

### ISSUE THREAD

**Issue by Emilemuny** [shoreditch-ops/artillery#292]
It'd be nice to be able to set the loop count to a variable instead of a static number. 
Use case: Ability to set how many transactions to create during a load test, setting this number in the config variable. e.g config.variables.numberOfTransactions = 5 usage in scenario:  {"loop": [], "count": "{{ numberOfTransactions }}"}

**Comment by hassy** [comment]
This can be done with the `whileTrue` hook now in Artillery `1.6.0-9`. Docs here:

https://artillery.io/docs/http-reference/#experimental-looping-with-custom-logic

**Comment by vegerot** [comment]
@hassy how does that help?  With your "fix" I would still need to make global variables for a counter, then in `whileTrue` increment the counter and check if it is above the maximum count I want, and if it is false then reset the counter and return false.
