### ISSUE TITLE
Local install gives error: TypeError: async.constant is not a function

### ISSUE THREAD

**Issue by jorisroling** [shoreditch-ops/artillery#296]
You might need to upgrade the async library to the current v1.5.2 (you seem to use certain newer functions already, like **constant**.

**Comment by hassy** [comment]
Artillery is using Async 1.5.2. Do you see the error when you install Artillery or when you try to run a test?

**Comment by jorisroling** [comment]
I did install it locally, within an existing nodejs project), and it ended up in node_modules/artillery/node_modules/async (v1.0.0), while the project itself had async (v1.5.2) already installed (node_modules/async)

Installing artillery globally works fine, but I'd like the project to be self contained (for CI purposes).

Regards,
J*

**Comment by hassy** [comment]
Interesting! Fixed in https://github.com/shoreditch-ops/artillery/commit/2cbc0e3283c24b356e17b03b466f96b157dd40aa now, but it's strange that `1.0.0` was getting installed rather than `1.5.2`.

Thanks @jorisroling

**Comment by jorisroling** [comment]
Thanks! 
Could you bump the version, and publish to npm?
