### ISSUE TITLE
Is it possible to determine which virtual user is running?

### ISSUE THREAD

**Issue by anders-brolien** [shoreditch-ops/artillery#297]
I'm trying to simulate a mass-user scenario. I would like each virtual user to give unique calls to the system (HTTP REST). What are the options for achieving this?

**Comment by hassy** [comment]
You can write a custom function to generate a UUID (using the `uuid` module for example) and send that along with the request, using the mechanism described here: https://artillery.io/blog/using-fakerjs-with-artillery

**Comment by anders-brolien** [comment]
Thanks! Will try it out. Looks promising.
