### ISSUE TITLE
config.environments

### ISSUE THREAD

**Issue by kostyamy** [shoreditch-ops/artillery#298]
Inability to specify config.environments property as a some sort of an external "include" json file while maintaining multiple test files becoming very annoying issue.  
Is it possible to add such feature to upcoming releases? Here is just a thought how it may look:  
```javascript
"config": {  
    ...
     "environments": "my-environments.json"   // if property is a sting and not an object then treat it as external json/yml file
    ...
}
```
I'm sure it would take only 15 minutes of work but would help a ton in our daily routine

**Comment by hassy** [comment]
How many environments are you dealing with @kostyamy? Does each environment has a lot of environment-specific settings as well?

**Comment by kostyamy** [comment]
It's not really about number of environments but rather test scripts. We have numerous .json test files i have to go through to update environment when change occurs. Also imagine when developer changes environment settings in number of scripts in repository log it still look like the scripts changed and now Q/A guys have to verify that no change in actual scenarios occurred.  So there are number of benefits having ability to specify not just environment but even entire "config" node as an external jons/yml file

**Comment by hassy** [comment]
Great, thanks for the extra context @kostyamy. The latest pre-release versions of Artillery support a new `--config` flag which takes a path to a JSON/YAML file containing the `config` definition for a test. That change allows for a common configuration to be extracted into a separate file, and keep scenarios in separate files. I think that will address your use case. You can install Artillery v1.5.8-1 to try it out (`npm install -g artillery@1.5.8-1`).

**Comment by hassy** [comment]
Oh and the issue tracker here is fine for feature suggestions and questions!
