### ISSUE TITLE
ReferenceError: url is not defined

### ISSUE THREAD

**Issue by rfphill** [shoreditch-ops/artillery#305]
Using the latest version of Artillery (and Node 5.9.1) I'm getting an error when adding a cookies to the GET scenario.  If I remove the cookie configuration the load test runs as it should.

I upgraded my project from an earlier version of Artillery 1.5.8.1 and that is when I started to see the error.  if I roll back to the original Artillery version my project was based on, the error goes away.

My config:
{
  "config": {
    "payload": "",
    "target": "http://img.yournamehere.com",
    "processor": "../src/artillery-test.js",
    "phases": [
      {
        "duration": 10,
        "arrivalRate": 10
      }
    ],
    "defaults": {
      "headers": {}
    }
  },
  "scenarios": [
    {
      "name": "basicTrafficLoad",
      "flow": [
        {
          "get": {
            "url": "/image.aspx?event=gtm.load&privateLabelId=1&status=200&app=cms&event_type=page.request&page=%2F&hw=2&browx=1426&browy=254&resx=1440&resy=900&cdepth=24&cv=loadtest&sitename=www.yournamehere.com&vs=visible&timestamp=1494603278230&corrid=1113351289&cvg=6818767c-edeb-9d92-e230-7bf99938482b&eventdate=2017-05-12T15:34:38.230Z&loadtestid=1494603278228&rand=1113351289&dcrOverride=true&gsOverride=true&sqlOverride=false&gaOverride=false",
            "cookie": {
              "traffic": "",
              "visitor": "vid=72585653-e91f-bd11-2370-0e24f538b1f3",
              "fb_sessiontraffic": "pathway=2be04b35-dad8-2d80-c935-ff4a2526a090"
            },
            "beforeRequest": "setJSONBody",
            "afterResponse": "logHeaders"
          }
        },
        {
          "think": 1
        },
        {
          "get": {
            "url": "/pageEvents.aspx?event_type=page.event&eventtype=impression&e_id=trafficloadtest.sales.%2F.domain_search.bug_bar_domain_search_banner_module.button.a9500377-07a9-4f9c-b430-2c9036072345&sitename=www.yournamehere.com&page=%2F&vs=visible&timestamp=1494603278230&corrid=1113351289&cvg=6818767c-edeb-9d92-e230-7bf99938482b&eventdate=2017-05-12T15:34:38.230Z&loadtestid=1494603278228&rand=1113351289&dcrOverride=true&gsOverride=true&sqlOverride=false&gaOverride=false"
          }
        },
        {
          "get": {
            "url": "/b.aspx?event_type=page.log&eventtype=pageperf&connectEnd=1492781447262&connectStart=1492781447262&domComplete=1492781448346&domContentLoadedEventEnd=1492781448163&domContentLoadedEventStart=1492781448163&domInteractive=1492781448162&domLoading=1492781447463&domainLookupEnd=1492781447262&domainLookupStart=1492781447262&fetchStart=1492781447262&navigationStart=1492781447261&requestStart=1492781447284&responseEnd=1492781447789&responseStart=1492781447436&loadEventStart=1492781448346&loadEventEnd=1492781448348&navigationType=1&event=gtm.load&privateLabelId=1&status=200&app=cms&sitename=www.yournamehere.com&page=%2F&vs=visible&timestamp=1494603278230&corrid=1113351289&cvg=6818767c-edeb-9d92-e230-7bf99938482b&eventdate=2017-05-12T15:34:38.230Z&loadtestid=1494603278228&rand=1113351289&dcrOverride=true&gsOverride=true&sqlOverride=false&gaOverride=false"
          }
        }
      ]
    }
  ]
}

**Comment by hassy** [comment]
Thanks for the bug report @rfphill! A fix is on its way. 🚢

**Comment by hassy** [comment]
Fixed in `v1.6.0-1`
