### ISSUE TITLE
Cannot set header in beforeRequest hook

### ISSUE THREAD

**Issue by thxmike** [shoreditch-ops/artillery#306]
Using version 1.6.0-1 on NodeJS - v6.8.0, I am attempting to use a beforeRequest hook to set the body and the header of a request. 
Here is example code:

    function setFileBody(requestParams, context, ee, next) {

        var file_path = file_paths[Math.floor(Math.random() * file_paths.length)];
        console.log(context);
        requestParams.body = fs.readFileSync(file_path).toString()
        requestParams.headers['filename'] = `${file_path.replace(/^.*[\\\/]/, '')}`
        console.log(requestParams)
        return next();

    }

I have also tried  requestParams.headers.filename = `${file_path.replace(/^.*[\\\/]/, '')}`

The body gets set as expected but the header does not. Based on debug mode it appears the header is overwritten when the request is posted.
Here is what the log indicates:

 http request: {
  "url": "http://cav-068-core-ubuntu-1.mia.ucloud.int:8008/file",
  "method": "POST",
  "headers": {
    "user-agent": "artillery 4.3.1 (https://artillery.io)"
  },
  "body": "%PDF-1.6\r%����\r\n104 0 obj\r<</Linearized 1/L 33789/O 107/E 24249/N 1/T 31645/H [ 1153 249]>>\rendobj\r               \r\nxref\r\n104 41\r\n0000000016 00000 n\r\n0000001574 00000 n\r\n0000001712 00000 n\r\n0000002005 00000 n\r\n0000002436 00000 n\r\n0000003136 00000 n\r\n0000003610 00000 n\r\n0000003744 00000 n\r\n0000003781 00000 n\r\n0000003827 00000 n\r\n0000004621 00000 n\r\n0000004772 00000 n\r\n0000004897 00000 n\r\n0000005740 00000 n\r\n0000006077 00000 n\r\n0000006907 00000 n\r\n0000007079 00000 n\r\n0000007835 00000 n\r\n0000008706 00000 n\r\n00 ..."
} +263ms

Based on the documentation, it appears headers are settable in the beforeRequest hook but for some reason it is overwritten in my case. Not sure if this is a bug or something I am doing incorrectly

**Comment by hassy** [comment]
Thanks for the bug report @thxmike. This should be fixed by https://github.com/shoreditch-ops/artillery-core/pull/177
