### ISSUE TITLE
RPS jump

### ISSUE THREAD

**Issue by cjmade** [shoreditch-ops/artillery#313]
I've noticed that Artillery jumps in number of **RPS** that it's making. For example I cannot make RPS between 330 and 480. It works fine on 330, but if I set RPS to be even 335 it will actually be sending 480 RPS.
I noticed it also on lower numbers as well, all settings between 100-140 will do 140RPS, etc.
Is this expected behavior? Can it be adjusted?

**Comment by hassy** [comment]
You can't set RPS with Artillery, can you show an example of the config that you're using?
