### ISSUE TITLE
Mustache cannot capture object drilled down?

### ISSUE THREAD

**Issue by tokidoki11** [shoreditch-ops/artillery#314]
Hi, I tried to capture an object and send some of the data to the next request

I found that in the mustache, you cannot send drilled down object e.g {{data.name}}. It will be sent that way, not the variable value. 
I can confirm that my data is captured well
The image below is captured using debug http

<img width="271" alt="screen shot 2017-06-27 at 12 31 15 am" src="https://user-images.githubusercontent.com/7564844/27552360-469e78ce-5ad1-11e7-8442-8c0b2ee1f5be.png">

But if I capture the value one by one like this
  - json: "$.data.name"
     as: "name"
  - json: "$.data.title"
      as: "title"
  - json: "$.data.company"
       as: "company"

and send it using {{name}} it will work. 

I think you should be able to send drilled down object.

Artillery Version: 1.6.0-2

**Comment by hassy** [comment]
Yes that's indeed not possible at the moment but should be supported.

**Comment by hassy** [comment]
This has been implemented in `v1.6.0-24`, closing. :)
