### ISSUE TITLE
If an attribute contains dash it will not capture element data

### ISSUE THREAD

**Issue by plofty** [shoreditch-ops/artillery#315]
Version - 1.6.0-2

I can capture authorization header & set BearerId to that value and this works OK but if I use Bearer-Id this does not work. Looks like artillery has an issue with dash symbol

If dash is not supported artillery should throw an error before running

**Working code example**
    - get:
        url: "{{ landingPage }}"
        headers:
          Accept-Language: "en-US,en;q=0.5"
        capture:
          header: "authorization"
          as: "BearerId"
    - get:
        url: "/test"
        headers:
          authorization: "{{ BearerId }}"

**Result**
"authorization": "Bearer 82ee99648123124...."

**Broken code example**
    - get:
        url: "{{ landingPage }}"
        headers:
          Accept-Language: "en-US,en;q=0.5"
        capture:
          header: "authorization"
          as: "Bearer-Id"
    - get:
        url: "/test"
        headers:
          authorization: "{{ Bearer-Id }}"

**Result**
"authorization": "{{ Bearer-Id }}"

**Comment by hassy** [comment]
`Bearer-Id` is not a valid JS identifier, that's why it does not work. Agree that Artillery should be more vocal about errors.
