### ISSUE TITLE
Capturing multiple json attributes works well with with json script but not in yml script

### ISSUE THREAD

**Issue by plofty** [shoreditch-ops/artillery#316]
Version - 1.6.0-2

I want to capture person ID, Name and Email from json response, this seems to work well with artillery script in json format but does not work well with yml format. With yml it only gets person name 

**test.json**
        {
          "get": {
            "url": "/test",
            "capture": [{
                "json": "$.person[0].personId",
                "as": "personId"
              },{
                "json": "$.person[0].personEmail",
                "as": "personEmail"
              },{
                "json": "$.person[0].personName",
                "as": "personName"
              }]
          }

**Result**
 http { personId: '123456', personEmail: 'test@test.com', personName: 'test 123456' } +1ms

**test.yml**
    - get:
        url: "/test"
        capture:
          json: "$.person[0].personId"
          as: "personId"
          json: "$.person[0].personEmail"
          as: "personEmail"
          json: "$.person[0].personName"
          as: "personName"

**Result**
  http { personName: 'test 123456' } +1ms

Only way I can get it to work is by converting json file to yml (below) but I believe the way I have scripted it above should work.
  - get:
      url: /test
      capture:
      - {json: '$.person[0].personId', as: personId}
      - {json: '$.person[0].personEmail', as: personEmail}
      - {json: '$.person[0].personName', as: personName}

**Comment by hassy** [comment]
Your YAML is wrong, arrays of objects need to have dashes in front of the first key e.g.:

```yaml
- get:
  url: "/test"
    capture:
      - json: "$.person[0].personId"
        as: "personId"
      - json: "$.person[0].personEmail"
        as: "personEmail"
```

That should work.
