### ISSUE TITLE
Bug: arrivalRate and arrivalCount in config are not respected in test run

### ISSUE THREAD

**Issue by ericmacfarland** [shoreditch-ops/artillery#325]
## Versions
Node: `v8.1.3`
Artillery: `v1.6.0-2`

## Backround
I have a `.yml` script that has the intent of running a high volume burst of requests. (See [example-file.txt](https://github.com/shoreditch-ops/artillery/files/1142361/example-file.txt))
Details:
- One phase with `duration: 1` and `arrivalCount: 340`
- Eight scenarios, each with one request

## Expected result
When the test is run, 340 scenarios should be fired

## Actual result
When the test is run, 500 scenarios are fired, final log below:
```
Complete report @ 2017-07-12T14:43:03.286Z
  Scenarios launched:  500
  Scenarios completed: 500
  Requests completed:  500
  RPS sent: 8.89
  Request latency:
    min: 42.8
    max: 54254.8
    median: 6674.8
    p95: 52835.3
    p99: 53474.8
  Scenario duration:
    min: 51.3
    max: 54266.4
    median: 6695.5
    p95: 52840
    p99: 53490
  Scenario counts:
    /api/user-settings/featureToggles: 76 (15.2%)
    /dashboard: 60 (12%)
    /api/dealer/dashboardCards: 81 (16.2%)
    /api/user-settings/profile: 54 (10.8%)
    /api/dealer/stepsToGrow: 60 (12%)
    /api/user-settings/users/{{ email }}: 57 (11.4%)
    /api/dealer/ensembleView: 54 (10.8%)
    /api/user-settings/ensembles?userId={{ user }}: 58 (11.6%)
  Codes:
    200: 500
```

The same thing happens when `arrivalCount: 240`, but the actual count is `250` scenarios fired.

**Comment by hassy** [comment]
Interesting, thanks for the bug report @ericmacfarland. What version of Artillery & Node.js is this?

**Comment by ericmacfarland** [comment]
@hassy I've updated my first post with my versions

**Comment by hassy** [comment]
Thanks. I'm able to reproduce the bug.

**Comment by ericmacfarland** [comment]
Thanks for the quick replies!

**Comment by hassy** [comment]
The bug's been fixed, the fix will be available in the next release of Artillery (to be published this week).

**Comment by ericmacfarland** [comment]
Fantastic, thanks!
