### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by jessebye** [shoreditch-ops/artillery#326]
I cannot find any indication in the documentation whether Artillery supports HTTP/2. Does it support it? If so, it would be very helpful to indicate that in the documentation. Going a bit further, if Artillery does support HTTP/2, it would also be helpful to add a flag to enable/disable it on a given test. That would allow for benchmarking HTTP/1.1 vs HTTP/2 with Artillery.

**Comment by hassy** [comment]
Artillery does not support HTTP/2 at the moment. It's on the roadmap but there's no ETA for it.

**Comment by jessebye** [comment]
I might suggest noting somewhere in the documentation that Artillery uses HTTP/1.1 and does not support HTTP/2. Thanks for clarifying this @hassy

**Comment by Textras** [comment]
Still not supporting?
