### ISSUE TITLE
Feature Proposal: Report Latencies by Scenario

### ISSUE THREAD

**Issue by dysn** [shoreditch-ops/artillery#332]
Hi,

I've been using artillery to test my application, and found that I wanted to see the request latencies by scenario. For instance, I have two scenarios, with about the same flow, but one makes a big request, and the other a small request.

It would be nice to be able to see the difference in the same load test, because then I could see whether the big requests are slowing down the small requests

I wrote code to implement this, but it is not quite ready (no tests, no flag to enable/disable), and I am not sure if it is the most elegant solution, but it works and I have been using it in my own tests.

Let me know if this is a feature you are interested in adding, and I will clean up what I have and put in a pr

**Comment by ericmacfarland** [comment]
Out of curiosity, does your code also enable per-request latency?

**Comment by dysn** [comment]
it does not, my use case didn't really need it

When you say per-request, do you mean something like

flow
   get
       url : someurl1
   get
       url : someurl2
   get
      url: someurl1


do you mean that the latencies would be by url (irrespective of scenario), or by order within a given scenario? Order seems more useful to me, and would be easy to index by (should be able to just use _successCount on the context), though I can see endpoint being useful as well.

**Comment by hassy** [comment]
This is probably better packaged up as a plugin, although the documentation for that is scant at the moment. There's also this @ericmacfarland - https://github.com/shoreditch-ops/artillery/issues/231#issuecomment-266814522 - which might do what you're after?
