### ISSUE TITLE
Artillery not getting properly installed on ubuntu 16.04

### ISSUE THREAD

**Issue by pranshu1595** [shoreditch-ops/artillery#333]
when running <sudo npm install -g artillery>, 
This gives npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/home/newgen/.npm-global/bin/artillery -> /home/newgen/.npm-global/lib/node_modules/artillery/bin/artillery
/home/newgen/.npm-global/lib
`-- artillery@1.6.0-2 

then when we run
<artillery dino>, this gives 
artillery: command not found
 
kindly help.

**Comment by hassy** [comment]
Looks like Artillery was installed with no problems but for some reason the binary is not in `$PATH`. This is an issue on your system, not an Artillery bug.

**Comment by wbrickner** [comment]
I have the exact same issue.  `artillery@1.6.0-13`.  Are you sure there's nothing about the npm installation which is subtly platform specific?  I also am on Ubuntu v16.04.  Could also be an NPM bug (v5.6.0).

**Comment by hassy** [comment]
Impossible to say without more information @wbrickner. Are you able to install another package that installs a global binary (e.g. `ghwd`) and use that? Are you seeing error messages during installation?

**Comment by wbrickner** [comment]
```
$ npm install -g ghwd
```
yields:
```
/home/will/node-v9.4.0-linux-x64/bin/g -> /home/will/node-v9.4.0-linux-x64/lib/node_modules/ghwd/bin/ghwd
/home/will/node-v9.4.0-linux-x64/bin/ghwd -> /home/will/node-v9.4.0-linux-x64/lib/node_modules/ghwd/bin/ghwd
+ ghwd@1.1.3
added 1 package in 2.679s
```
but afterwards:
```
$ ghwd
```
yields:
```
No command 'ghwd' found, did you mean:
 Command 'gwd' from package 'geneweb' (universe)
ghwd: command not found
```

**I ended up fixing the artillery issue by manually forming a symlink to the binary.**  

After installing, npm tells me it's in `<YOUR_NODE_INSTALL_DIRECTORY>/lib/node_modules/artillery/bin/artillery`.

I make it available anywhere by doing:
`sudo ln -s <YOUR_NODE_INSTALL_DIRECTORY>/lib/node_modules/artillery/artillery /usr/local/bin/artillery`

Cheers.

**Comment by hassy** [comment]
Yes that confirms that the issue is with your system settings, not Artillery (or another npm package). You need to add `/home/will/node-v9.4.0-linux-x64/bin/` to `$PATH`.

**Comment by hajimurtaza** [comment]
Your issue is related to incorrect installtion of npm. This usually happens when sudo is used to install npm. 
As it loads all global node modules from the root directory by creating a `.npm-global` package.
Hence you are able to install packages globally but not be able to use them

Try running` npm config get prefix`
if u get an output anything other then` /usr/local` , that means you need to reconfigure your npm install

**Comment by vijayakumar-psg587** [comment]
I experience a similar problem, but was able to resolve it by adding the node executable path to the system variable. Get the exec path by using `which node`. The add that to the environment variable PATH
`PATH=$PATH:/<your exec bin location>`
and now try to install artillery globally. You should be able to get that started
