### ISSUE TITLE
typo in docs: Script Ref -> config -> Fixed count of arrivals

### ISSUE THREAD

**Issue by eranegozy** [shoreditch-ops/artillery#339]
Should mention 'arrivalCount', instead of 'arrivalRate', I believe.

**Comment by ericmacfarland** [comment]
To add more context, I believe this is the section that is referred to by the OP, under the examples for `config.phases`

----
![image](https://user-images.githubusercontent.com/26652326/29190008-2f8fe7e6-7dde-11e7-816a-d053dfeb3440.png)

**Comment by hassy** [comment]
Thanks! fixed
