### ISSUE TITLE
I need the mean value in the report. It currently  gives min, max, median for latency and scenarioDuration. Or atleast I should be able to get response times for all the requests made so that I can compute the mean by myself.

### ISSUE THREAD

**Issue by cskru** [shoreditch-ops/artillery#341]
Mean of the response times for all the scenarios would be a great weapon.
So, is there a way to somehow get it by tweaking in some code?

Or, it'll be helpful if I can get the response times for all the requests. I can compute the Mean by myself.
Is there a way to get the response times (scenarioDuration) for all the requests made?

**Comment by hassy** [comment]
means are not very useful for measuring latency in my experience, having said that if that's something you really need, it should be possible to do with a custom plugin (e.g. see https://github.com/shoreditch-ops/artillery-plugin-statsd)

**Comment by cskru** [comment]
I really need the mean value.
It is the average of time elapsed for all request/responses.
If not exactly the mean, I atleast need the time elapsed for all the request/responses.

How do I get the time elapsed for each individual scenario?
Example:
Summary report @ 10:56:14(+0530) 2017-09-01
  Scenarios launched:  10000
  Scenarios completed: 10000
  Requests completed:  10000
  Concurrent users:    164454
  RPS sent: 194.82
  Request latency:
    min: 36.9
    max: 33328.9
    median: 16262.1
    p95: 32182.9
    p99: 33130.4
  Scenario duration:
    min: 48.2
    max: 33330.3
    median: 16265
    p95: 32184.4
    p99: 33132.4
  Scenario counts:
    0: 10000 (100%)
  Codes:
    200: 10000

In here, I am focusing on:
Scenario duration:
    min: 48.2
    max: 33330.3
    median: 16265
    p95: 32184.4
    p99: 33132.4

Here, I require the mean. Or if I get to know the scenario duration for every scenario launched, I'll be more than happy.
Please let me know how to get that.

**Comment by hassy** [comment]
See the link to the statsd plugin posted above.
