### ISSUE TITLE
Failing a scenario/virtual user gracefully

### ISSUE THREAD

**Issue by mikebell** [shoreditch-ops/artillery#344]
I have a long running HTTP load test that runs through a multipage form. There's a custom function that returns an ID there's a small chance it might not be found (not something I can control).

At the moment if that ID isn't found Artillery shuts down with "Unexpected error, Artillery shutting down.". Is there any way of catching this (maybe in the custom JS function) so it doesn't exit out and the other scenarios/virtual users can carry on? Currently my load test is running between 10-15 minutes so it sucks to lose all that data up until the point it exits.

**Comment by hassy** [comment]
Passing an `Error` into the callback will abort the virtual user gracefully (and the error code will be included in the report).

**Comment by tiffanywilson** [comment]
@hassy @mikebell Can one of you give an example of how this should work? I'm currently doing the following: 

```  function exitOnFail(req, response, context, events, next, error) {
    if (response.statusCode == '404') {
      console.log("Exit on 404 Error");
      return next(error);
    }
    else {
      return next();
    }```

It will log the message to my report, but it doesn't actually exit the scenario.

**Comment by hassy** [comment]
You need to create an instance of `Error` in the function and pass that into the callback @tiffanywilson, so e.g.:

```javascript
function exitOnFail(req, response, context, events, next) { // remove the extra argument here
    if (response.statusCode == '404') {
      console.log("Exit on 404 Error");
      return next(new Error('statusCode is 404'));
    }
    else {
      return next();
    }
```

**Comment by tiffanywilson** [comment]
That worked. Thanks for the quick response!
