### ISSUE TITLE
on mac install ,and bash artillery run hello.yml

### ISSUE THREAD

**Issue by yangguang314** [shoreditch-ops/artillery#351]
/usr/local/bin/artillery: artillery: line 9: syntax error near unexpected token `('
/usr/local/bin/artillery: artillery: line 9: `const debug = require('debug')('artillery:cli');'

**Comment by hassy** [comment]
Can't reproduce the problem here on OSX & bash. What happens when you run 

```
node `which artillery`
```

**Comment by Luidog** [comment]
I am having the same issue. I ran `node `which artillery``

which returned:

`
  Usage: artillery [options] [command]


  Commands:

    run [options] <script>   Run a test script. Example: `artillery run benchmark.json`
    quick [options] <url>    Run a quick test without writing a test script
    report [options] <file>  Create a report from a JSON file created by "artillery run"
    convert <file>           Convert JSON to YAML and vice versa
    dino [options]           Show dinosaur of the day

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
`

**Comment by hassy** [comment]
Interesting, @Luidog if you run "node `which artillery`" do you see Artillery's help message being printed?

I can't reproduce - anyone else having a similar issue, could you try running the command above and also post your:

- Node.js version (`node -v`)
- version of Artillery you're trying to run
- OS version and shell

**Comment by pfadiaz** [comment]
I can reproduce the issue and I can see the Artillery's help message when running node `which artillery`

 Here is my info:

- Node.js version => v7.10.0
- Output of /usr/bin/env node -v => v7.10.0
- version of Artillery you're trying to run => 1.6.0-6
- OS version and shell => macOS Sierra 10.12.6 (16G29) / zsh 5.2 (x86_64-apple-darwin16.0)

After running these commands:  

bash artillery run hello.yml

OR the quick one:

bash artillery quick --count 10 -n 20 https://artillery.io/

Result:

/usr/local/bin/artillery: line 3: /Applications: is a directory
/usr/local/bin/artillery: line 4: hello.yml: command not found
/usr/local/bin/artillery: line 5: hello.yml: command not found
/usr/local/bin/artillery: line 7: use strict: command not found
/usr/local/bin/artillery: artillery: line 9: syntax error near unexpected token `('
/usr/local/bin/artillery: artillery: line 9: `const debug = require('debug')('artillery:cli');'

**Comment by hassy** [comment]
@pfadiaz `artillery` is not a shell script, it's JS code so running it with `bash` isn't going to work.

What does `which node` print on your machine?

**Comment by pfadiaz** [comment]
@hassy thanks! 
which node output=>  /usr/local/bin/node
I'm now able to execute my .yml scripts. By mistake I used the bash command.

**Comment by hassy** [comment]
No worries @pfadiaz, still puzzled by the issues the others are seeing though.

**Comment by olingern** [comment]
I ran into this same issue. Following[ the docs](https://artillery.io/docs/getting-started/), you'll find:

`bash artillery run hello.yml`

which doesn't seem to be correct.

`artillery run hello.yml`

would seem to be the desired command

**Comment by hassy** [comment]
Ah that explains it (Markdown formatting fail), thanks @olingern!
