### ISSUE TITLE
Need a clear understanding on artillery output as to what the terms mean in elements.

### ISSUE THREAD

**Issue by cskru** [shoreditch-ops/artillery#358]
What is Request Latency and Scenario Latency. I mean what is the difference between them.
From the source code I can see that stats of scenarioDuration are calculated based on _scenarioLatencies.
And, the stats of Request Latency are calculated based on a variable called latency.

For scenarioDuration:
`result.scenarioDuration = {
    min: round(L.min(this._scenarioLatencies) / 1e6, 1),
    max: round(L.max(this._scenarioLatencies) / 1e6, 1),
    median: round(sl.median(this._scenarioLatencies) / 1e6, 1),
    p95: round(sl.percentile(this._scenarioLatencies, 0.95) / 1e6, 1),
    p99: round(sl.percentile(this._scenarioLatencies, 0.99) / 1e6, 1),
  };`

For request latency:
`result.latency = {
    min: round(L.min(latencies) / 1e6, 1),
    max: round(L.max(latencies) / 1e6, 1),
    median: round(sl.median(latencies) / 1e6, 1),
    mean: round(sl.mean(latencies) / 1e6, 1),
    p95: round(sl.percentile(latencies, 0.95) / 1e6, 1),
    p99: round(sl.percentile(latencies, 0.99) / 1e6, 1)
  };`

I inspected the arrays _scenarioLatencies and latencies. I want to know more on them.
Suppose I give a pool:10, does _scenarioLatencies consider (waiting time + elapsed time) to calculate min, max, etc? I request you to explain this a little in detail.

By waiting time I mean, If the pool size is 10 and the arrival rate is 10000, it creates a batch of 10 requests and populates the batch once a response has arrived.

So, here, waiting time comes into picture.

So, I request you to explain more about it, since it's little confusing and we can go further and improve the documentation of artillery itself.

Thanks,
Kruthika

**Comment by hassy** [comment]
Scenario duration is a breakdown of how long virtual users take to complete an entire scenario. Those are based on latencies of individual requests (response time + network time) in a particular execution of a scenario plus waiting time.

**Comment by cskru** [comment]
Thank you for the response Hassy.
Is there a way to extract just the elapsed times (response time + network time only).
Currently I have this and I believe it gives elapsed time only:

`scenarios:
  - afterResponse: "afterScenario"
    beforeRequest: "beforeScenario"
    flow: ......`

`function beforeScenario(requestParams, context, ee, done) {
    startTime = Date.now();
    return done();
}

function afterScenario(requestParams, response, context, ee, done) {
    console.log(response.body);
    endTime = Date.now();
    elapsedTimeArray.push(endTime - startTime);
    if(elapsedTimeArray.length === 10000) { //Set this num in arraivalRate too. Example: 10000
        console.log(elapsedTimeArray.length+' elapsedTimeArray:' + elapsedTimeArray);
        console.log("Mean: "+stats.mean(elapsedTimeArray));
    }
    return done();
}`

So, in the above code, elapsedTimeArray has 10000 entries (endTime - startTime) of each request.

This gives on the elapsed time right?
Also, if I can extract only elapsed time (Shouldn't have the trace of waiting time at all when pool is mentioned) from artillery source code itself somehow, please let me know.
This is much needed.
