### ISSUE TITLE
What happened to the docs?

### ISSUE THREAD

**Issue by olingern** [shoreditch-ops/artillery#367]
User of artillery in the past and was looking for documentation on writing functions for generating dynamic content. The current docs seem super sparse compared to what they were 6+ months ago.

Perusing through the [shoreditch-ops artillery channel](url), I get tons of 404's
https://artillery.io/docs/script_reference.html#payloads
https://artillery.io/docs/testing_http.html#advanced-writing-custom-logic-in-javascript

The wayback archive does show me what I'm looking for:
https://web.archive.org/web/20170626015503/https://artillery.io/docs/testing_http.html#advanced-writing-custom-logic-in-javascript

Has there been significant functionality deprecated, or is there a different reason the docs are so sparse now?

**Comment by hassy** [comment]
The URLs did change at one point, but all content is still there - https://artillery.io/docs/
