### ISSUE TITLE
$loopCount returns nothing in the websocket test context

### ISSUE THREAD

**Issue by jeco123** [shoreditch-ops/artillery#368]
Hi,
Here is my loop, sending 10 message of json  {"type": "subscribe", "payload": xxx}
-------------      
 - loop:
          - send:
              type: "subscribe"
              payload: "{{ $loopCount }}"
          count: 10
-------------
The problem is the $loopCount contains an empty or undefined? value. With the http engine, the loopCount variable works.

**Comment by hassy** [comment]
Thanks for the bug report @jeco123

**Comment by jeco123** [comment]
Tanks ;-)
