### ISSUE TITLE
phases settings

### ISSUE THREAD

**Issue by nnnikolay** [shoreditch-ops/artillery#375]
Hello, 

Could you please explain a bit how that section is working? because from the documentation it's not clear for me.

I have the following config
```
  phases:
    - duration: 120
      arrivalRate: 1
```

Which I would understand as "within 2 minutes increase concurrency from 0 to 120 of virtual users"
is that means that on the 5th second we would have 5 virtual users in total or 5 virtual users will be added to current amount? Which means on the 5th second we would have already 15th virtual users.

Here is the output of the last two reports

```
Report @ 10:36:41(+0200) 2017-09-25
  Scenarios launched:  1
  Scenarios completed: 5
  Requests completed:  19
  Concurrent users:    4
  RPS sent: 3.76
  Request latency:
    min: 84.1
    max: 1665
    median: 657.1
    p95: 1619.5
    p99: NaN
  Scenario duration:
    min: 3187.8
    max: 3927
    median: 3813.4
    p95: NaN
    p99: NaN
  Codes:
    200: 13
    201: 6

All virtual users finished
Summary report @ 10:36:41(+0200) 2017-09-25
  Scenarios launched:  120
  Scenarios completed: 120
  Requests completed:  600
  Concurrent users:    635
  RPS sent: 4.9
  Request latency:
    min: 83.1
    max: 3764.2
    median: 773.9
    p95: 2307.9
    p99: 3013.8
  Scenario duration:
    min: 3187.8
    max: 8851.6
    median: 4716.2
    p95: 7373.7
    p99: 8785.9
  Scenario counts:
    order request: 120 (100%)
  Codes:
    200: 360
    201: 240
```

I mean for me is quite hard to make a conclusion in the report (apart from that the requests are slow by them self obviously).

I've only one scenario which consists from 5 http reqs.
I see that 120 scenarios completed, but what is confusing me is a number of parallel users .. 635, really? And these guys were able to finish only 120 scenarios?

Looks like either I don't understand something or misconfigured, I would highly appreciate your help in understanding this.

Thanks

**Comment by hassy** [comment]
635 concurrent users being reported is a bug. Thanks for reporting that @nnnikolay.

```yaml
  phases:
    - duration: 120
      arrivalRate: 1
```

The meaning of this phase is "spawn 1 virtual user every second for 120 seconds". The number of concurrent users on second `N` depends on what the users do (the scenario definition). For example: if each user only makes 1 HTTP request which is served very quickly, you may not have more than 1 concurrent users at any given point. However, if you have a `think: 200` in your scenario definition, then once the load phase ends, you will have 120 concurrent users.

Does that make sense?

**Comment by nnnikolay** [comment]
Frankly, I was not able to find out `think:` definition in the documentation. Therefore I'm not sure that I understand why we will end up with 120 concurrent users. Could you please point me to the doc where it says what is that?

with `arrivalRate` is clear now, thanks.

One more question:

```
Report @ 12:00:06(+0200) 2017-09-25 
...
All virtual users finished
Summary report @ 12:03:16(+0200) 2017-09-25
```

I was expecting to have a load test for a 60 sec with the following settings:

```
    - duration: 60
      arrivalRate: 3
```

Why did it take 3 minutes? Because it was waiting when for all the requests are responded?



And another question is: which report's value should I use as an orienteer `RPS sent`? I mean what is the best practice in your opinion.
 
And last one: how could I know how many (in total) users has passed the scenario (`Scenarios completed`?)? 

In the final report I see following numbers:
```
Summary report @ 12:03:16(+0200) 2017-09-25
  Scenarios launched:  180
  Scenarios completed: 50
  Requests completed:  550
  Concurrent users:    17469
  RPS sent: 2.76
  Request latency:
    min: 142.8
    max: 60234.1
    median: 30216.9
    p95: 59884
    p99: 60205.5
  Scenario duration:
    min: 10281
    max: 175389.5
    median: 137088.8
    p95: 174195.5
    p99: 175389.5
  Scenario counts:
    order request: 180 (100%)
  Codes:
    200: 204
    201: 185
    504: 161
```

I see that there were 180 scenarios launched but only 50 is completed, means successfully or in general? And if in general what has happened with others?


btw, just in case

```
artillery --version
1.6.0-9
```

Sorry, for so many questions :-)
