### ISSUE TITLE
Artillery shows infinite "pending scenarios/requests" while running

### ISSUE THREAD

**Issue by anoasis** [shoreditch-ops/artillery#379]
I see pending scenarios/requests message keep spinning and never gets completed in my environment(behind the corp proxy with HTTP_PROXY env variable configured accordingly). I am running it with your latest version:
artillery version: v1.6.0-9
nodejs version: v8.3.0
npm version: v5.3.0

```
{
	"config": {
		"target": "http://url.com",
		"phases": [{
				"duration": 1,
				"arrivalRate": 1
			},
			{
				"duration": 1,
				"arrivalRate": 1
			},
			{
				"duration": 1,
				"arrivalRate": 1
			}
		],
		"processor": "./processor.js",
		"payload": [{
			"path": "./data.csv",
			"fields": ["id", "field1", "field2", "field3"]
		}]
	},
	"scenarios": [{
		"beforeRequest": ["preProcessHandler"],
		"afterResponse": ["postProcessHandler"],
		"flow": [{
				"get": {
					"headers": {
						"ID": "{{id}}",
						"Content-Type": "application/json"
					},
					"url": "/action/{{field1}}}"
				}
			},
			{
				"get": {
					"headers": {
						"ID": "{{id}}",
						"Content-Type": "application/json"
					},
					"url": "/action/{{field1}}}/{{field2}}"
				}
			},
			{
				"post": {
					"headers": {
						"ID": "{{id}}",
						"Content-Type": "application/json"
					},
					"url": "/action/{{field1}}",
					"json": {
						"payload": {
							"sample": "{{field3}}"
						},
						"date": "2017-08-01"
					}
				}
			}
		]
	}]
}
```

And, here is what I am getting as debug logs which shows the same symptom as the previously [closed issue #215 ](https://github.com/shoreditch-ops/artillery/issues/215) :
>   phases creating a uniform process for arrivalRate +4ms
  arrivals tickInterval = 1000, duration = 1000 +0ms
  arrivals this._tickInterval set to 1000000 +1ms
  arrivals maxArrivals = 1 +0ms
Started phase 0, duration: 1s @ 15:45:56(-0400) 2017-09-26
â ¹   runner picking scenario 0 (undefined) weight = 1 +1s
  perf runScenarioDelta: 6.9 +3ms
  arrivals maxArrivals reached, stopping +1s
  phases creating a uniform process for arrivalRate +4ms
  arrivals tickInterval = 1000, duration = 1000 +2ms
  arrivals this._tickInterval set to 1000000 +0ms
  arrivals maxArrivals = 1 +0ms

> Started phase 1, duration: 1s @ 15:45:57(-0400) 2017-09-26
>   processor process start +1s
> ===keep repeating======================================
> /   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> /   runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +4ms
> /   runner Pending requests: 0 +501ms
>   runner Pending scenarios: 3 +2ms
> /   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +3ms
> \   artillery:runner busyPids: +3s []
> |   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +2ms
> |   runner Pending requests: 0 +501ms
>   runner Pending scenarios: 3 +2ms
> |   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +2ms
> |   runner Pending requests: 0 +505ms
>   runner Pending scenarios: 3 +4ms
> -   artillery:runner max worker concurrency: {"12896":3} +2s
> Report @ 16:02:24(-0400) 2017-09-26
>   Scenarios launched:  3
>   Scenarios completed: 0
>   Requests completed:  0
>   Concurrent users:    3
>   RPS sent: NaN
>   Request latency:
>     min: NaN
>     max: NaN
>     median: NaN
>     p95: NaN
>     p99: NaN
>   Scenario duration:
>     min: NaN
>     max: NaN
>     median: NaN
>     p95: NaN
>     p99: NaN
> 
> \   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> -   artillery:runner busyPids: +623ms []
> \   runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +3ms
> \   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +2ms
> \   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +3ms
> \   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> -   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> /   artillery:runner busyPids: +3s []
> -   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +1ms
> -   runner Pending requests: 0 +505ms
>   runner Pending scenarios: 3 +2ms
> -   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +3ms
> -   runner Pending requests: 0 +501ms
>   runner Pending scenarios: 3 +2ms
> -   runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +4ms
> |   artillery:runner busyPids: +2s []
> -   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> /   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +4ms
> /   runner Pending requests: 0 +505ms
>   runner Pending scenarios: 3 +2ms
> /   runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +3ms
> /   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +1ms
>     runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +39s
> \   artillery:runner max worker concurrency: {"12896":3} +41s
> Report @ 16:03:11(-0400) 2017-09-26
>   Scenarios launched:  0
>   Scenarios completed: 0
>   Requests completed:  0
>   Concurrent users:    3
>   RPS sent: NaN
>   Request latency:
>     min: NaN
>     max: NaN
>     median: NaN
>     p95: NaN
>     p99: NaN
>   Scenario duration:
>     min: NaN
>     max: NaN
>     median: NaN
>     p95: NaN
>     p99: NaN
> 
> -   artillery:runner busyPids: +49ms []
> /   runner Pending requests: 0 +501ms
>   runner Pending scenarios: 3 +3ms
> -   artillery:runner busyPids: +536ms []
> /   runner Pending requests: 0 +501ms
>   runner Pending scenarios: 3 +2ms
> /   runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +4ms
> /   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +2ms
> /   runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +3ms
> |   runner Pending requests: 0 +501ms
>   runner Pending scenarios: 3 +3ms
> /   artillery:runner busyPids: +3s []
> |   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> |   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +3ms
> |   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> |   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> |   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +2ms
>   artillery:runner busyPids: +3s []
> |   runner Pending requests: 0 +505ms
>   runner Pending scenarios: 3 +2ms
> \   runner Pending requests: 0 +501ms
>   runner Pending scenarios: 3 +3ms
> \   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +2ms
> \   runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +2ms
> \   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +2ms
>   artillery:runner busyPids: +3s []
> \   runner Pending requests: 0 +503ms
>   runner Pending scenarios: 3 +4ms
> \   runner Pending requests: 0 +504ms
>   runner Pending scenarios: 3 +3ms
> \   runner Pending requests: 0 +502ms
>   runner Pending scenarios: 3 +2ms
> ===keep repeating======================================

**Comment by hassy** [comment]
Thanks for the detailed report @anoasis. From the log it looks like Artillery is waiting for all 3 virtual users to finish. The first thing I'd check is whether the custom functions (`preProcessHandler` and `postProcessHandler`) both always call back to return to control to Artillery. Another thing to check is whether either of them might be throwing an error somewhere.

**Comment by anoasis** [comment]
I had tried without the custom functions but I have found no luck. It looks like the custom functions are not even invoked since there is no logs getting printing in the console. I found nothing while also trying to try-catch an exception while the custom functions are getting called. 

Here is the code:
`'use strict';

const debug = require('debug')('processor');
const proxy_url = 'http://myproxyurl:8080/';
debug('booting processor');
var request = require('request');

module.exports = {
  preProcessHandler: preProcessHandler,
  postProcessHandler: postProcessHandler,
  printReqLogs: printReqLogs,
  printRespLogs: printRespLogs,
  createNewVar: createNewVar,
  rewriteUrl: rewriteUrl
};

function preProcessHandler(requestParams, context, ee, next) {
  try {
    debug('process start');
  catch (err) {
    debug('exception wihle preProcess');
  }
}

function postProcessHandler(requestParams, reponse, context, ee, next) {
  try {
    printReqLogs(requestParams, context, ee, next);
    printRespLogs(requestParams, reponse, context, ee, next);
  catch (err) {
    debug('exception wihle postProcess');
  }
}

function printReqLogs(requestParams, context, ee, next) {
  debug('[proxy] '+requestParams.proxy);
  debug('['+requestParams.method+'] '+requestParams.url);
  debug('[Headers] '+JSON.stringify(requestParams.headers));
}

function printRespLogs(requestParams, reponse, context, ee, next) {
  debug('['+response.statusCode+'] '+response.data);
}

// Ref: https://github.com/shoreditch-ops/artillery/issues/184
// See hello.json - testing that scenario-level beforeRequest is handled
// correctly.
function doNothing(requestParams, context, ee, next) {
  return done();
}

// this function is called in a loop
function createNewVar(context, ee, next) {
  ctx.vars.newVar = ctx.vars.$loopCount;
  console.log(`createNewVar: ${ctx.vars.$loopCount}`);
  return done();
}

function rewriteUrl(requestParams, context, ee, next) {
  req.url = '/';
  return done();
}
`

**Comment by hassy** [comment]
OK thanks @anoasis. `postProcessorHandle` not being invoked is interesting. Have you ruled the HTTP proxy as a possible issue? How long do you leave Artillery running for? Could you try rerunning the script with a short HTTP timeout setting, e.g.:

```json
{
  "config": {
    "http": {
      "timeout": 10
    }
}
```

**Comment by anoasis** [comment]
@hassy I figured out that it's due to the restriction of my corp internal network policy. Thanks for your help! :)

**Comment by hassy** [comment]
What was the restriction? (if you're able to elaborate) Would be nice if Artillery could try to detect such conditions and warn the user.

**Comment by anoasis** [comment]
@hassy Thanks for following up on this. I am still waiting for my corp network team to tell me what's going on our firewall policy. I will give out more details(within the allowable range) once I get the answer from them.

**Comment by hassy** [comment]
Going to close this for now but if you're able to share more information at some point please do @anoasis
