### ISSUE TITLE
Question about using params in body 

### ISSUE THREAD

**Issue by oscarmullin** [shoreditch-ops/artillery#382]
Hi,
I have the following scenario:

"post": {
            "url": "/someURL?caller.id={{ callerId }}",
            "json":{"callerId": "{{callerId}}"},
            "beforeRequest": "generateRandomData"
}

I am generating callerId in the generateRandomData function in a JS file elsewhere and everything works fine. However, the problem I have is that both callerIds should match (the one in the url and the one in the body).
However, the one in the URL is interpreted as a number (which is 100% correct), but in the json shows as a string.
Example, would be someURL?caller.id=1234 and json would look like {"callerId": "1234"}.

This causes a mismatch. My question is, how can I make the param in the json behave as a number?
I've already tried   "json":{"callerId": {{callerId}}} , but this generates and invalid JSON.

Any idea would be very appreciated.

Thanks!

**Comment by hassy** [comment]
Hi @oscarmullin. Right now, the only way to do what you need is to set the parameter inside a hook function. There's an example in this related issue: https://github.com/shoreditch-ops/artillery/issues/250

**Comment by oscarmullin** [comment]
Awesome. Very simple! Thanks a lot. BTW we will be writing a hub <-> nodes platform to do distributed load tests with artillery. Once ready, we will share.

Thanks
