### ISSUE TITLE
Global installation on Windows 10 failed

### ISSUE THREAD

**Issue by danorr** [shoreditch-ops/artillery#387]
Hi there, just tried running the global installation on Windows 10 and received the following error:

rolex@1.0.0 requires a peer of bower@* but none was installed.

I've looked up rolex module but couldn't see any mention of the dependency to bower. I take it that when a dependency isn't met, the whole library isn't installed. Is that right?

I've read that dependencies are no longer installed by default. I'm running npm 3.10.10.

Any help would be much appreciated.

**Comment by hassy** [comment]
`bower` is optional, Artillery should still work. Have you checked if you're able to run `artillery -V` for example?

**Comment by danorr** [comment]
I've run that in Powershell and get a 'term not recognised' error message. I've also tried in Bash for Windows with the same result.

**Comment by hassy** [comment]
Okay. Were there any error messages printed by `npm install`? Are you able to install and run another package globally, e.g. `npm install -g ghwd`?

**Comment by danorr** [comment]
Yes, I can install other software. I checked the npm folder in Roaming folder under my profile and can see that artillery has been installed. I've also fired up the npm shell and confirmed that artillery has been installed. It appears new modules don't get added to the path automatically - a wrong assumption on my part.

Thanks for your help.
