### ISSUE TITLE
Ability to send headers during Socket.IO handshake

### ISSUE THREAD

**Issue by maxjanisse** [shoreditch-ops/artillery#388]
My application requires that an identification cookie be provided during the initial handshake request with the Socket.IO server.  I noticed that the Socket.IO client was recently updated to a version that supports this functionality, so now it's just a matter of having a way to define these headers for the handshake request.

I was able to hack together a working solution by defining a *socketHeaders* section to the *scenario* object and then ensuring it get's passed all the way down to the *loadContextSocket* method, where it defines the *extraHeaders* option for Socket.IO.  

I have very little confidence that my solution is the best it could be.  You can see it in my fork of *artillery-core*.

**Comment by hassy** [comment]
It's taken a looooooong time, but the docs have been updated. :)
