### ISSUE TITLE
using json files as payload

### ISSUE THREAD

**Issue by gioragutt** [shoreditch-ops/artillery#391]
Currently, All I see is the ability to use a CSV as payload.

Say I have a bunch of JSON files, or just a json file, and I want to use its content as payload for requests.
Is that currently possible?

**Comment by hassy** [comment]
You could load your JSON in a hook function and then use the values - https://artillery.io/docs/http-reference/#advanced-writing-custom-logic-in-javascript

**Comment by gioragutt** [comment]
Thanks man, it took me some time to understand some stuff, mostly due to lacking docs, but I ended up working it out.
