### ISSUE TITLE
Pass multiple content to same URL in different request

### ISSUE THREAD

**Issue by meerarathesh** [shoreditch-ops/artillery#394]
I am new to artillery and need help in scripting.
I would like to pass below parameters as body for my API test.
{
  "SomeID": "00503",
  "filepath": "path://somefilepath/filename.xml",
  "ID": "XXX"
}
My code would look like below:
scenarios:
    - name: "Write to  table"
      flow:
      - post:
          url: "/test/t"
          headers: 
             Accept: "test/json"
             Content-Type: "application/json"
          body:
Need to pass three parameters mentioned first as body.Can someone help? Also need to test with different file paths and ID's.

**Comment by hassy** [comment]
Read the docs please - https://artillery.io/docs/http-reference/#get-post-put-patch-delete-requests
