### ISSUE TITLE
Generated report html pages using browser CPU

### ISSUE THREAD

**Issue by cbarbara-okta** [shoreditch-ops/artillery#401]
Anytime I load up one of the generated report html pages the browser (both chrome & safari) eats up CPU.

<img width="758" alt="screen shot 2017-11-09 at 4 13 11 pm" src="https://user-images.githubusercontent.com/2286573/32636384-68b70ac2-c569-11e7-81de-f79a60be1b14.PNG">

It looks to be coming from the included ace.js library:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ace.js" charset="utf-8"></script>`
<img width="1200" alt="screen shot 2017-11-09 at 4 13 44 pm" src="https://user-images.githubusercontent.com/2286573/32636402-7b5fc95c-c569-11e7-8170-5edfe34e9b73.PNG">

<img width="530" alt="screen shot 2017-11-09 at 4 13 53 pm" src="https://user-images.githubusercontent.com/2286573/32636408-7fbe6ca6-c569-11e7-9ac6-18079a106186.PNG">

**Comment by hassy** [comment]
I'm guessing you're looking at a report from a long and/or high RPS test? The raw JSON of the entire report is displayed at the bottom of the report, which for a large one would probably make Ace use a lot of CPU.

**Comment by cbarbara-okta** [comment]
The report was from a 5 minute run, mean RPS of 60.

**Comment by vishalbiradar** [comment]
@cbarbara-okta I am unable to see the reports.
Where it will be generated ?? And how to view it.
Will please help me.
Here is the link to  [My Issue regarding reports:](https://github.com/shoreditch-ops/artillery/issues/408)
