### ISSUE TITLE
What's the max arrivalRate supported by a single instance of artillery?

### ISSUE THREAD

**Issue by edwmurph** [shoreditch-ops/artillery#404]
What is the current limit on the amount of requests per second that a single instance of artillery can deliver? Though experimentation, I found that I can't deliver more than 450. Is that likely because of artillery or something else in my environment?

**Comment by hassy** [comment]
There's no inherent limit in Artillery itself, the arrival rate (and requests per second) depends on too many factors - both environmental e.g. the amount of CPU resources available to Artillery, and the tests themselves, e.g. a test script that runs computation-heavy custom JS code will put a lower limit on the arrival rate/RPS.

**Comment by edwmurph** [comment]
That makes sense thanks

**Comment by hassy** [comment]
Some official baseline benchmarks would certainly be useful to provide guidance for planning larger load tests.
