### ISSUE TITLE
Any Plans for GRPC support?

### ISSUE THREAD

**Issue by hartmut-co-uk** [shoreditch-ops/artillery#414]
Hi, 

I would be interested in load testing grpc - are there any plans to potentially support this in the future?

Thanks

**Comment by hassy** [comment]
Yes it's definitely something we'd look to make available through Artillery with the increasing popularity of gRPC in modern microservice-based architectures. No particular date on it at the moment though.

**Comment by idangozlan** [comment]
any news about it? thanks :)

**Comment by unludo** [comment]
Hi, we need grpc and grpc-web.

**Comment by kenju** [comment]
Hi 👋I'm working on developing an engine for gRPC

👉 https://github.com/kenju/artillery-engine-grpc

Still **this is in early stage**, it works perfectly with single proto file & single service.

See https://github.com/kenju/artillery-engine-grpc/pull/2 and [sample/ directory](https://github.com/kenju/artillery-engine-grpc/tree/master/sample) to see how it works.

**Comment by kenju** [comment]
Hi 👋 

I'm working on https://github.com/kenju/artillery-engine-grpc to add gRPC support for artillery.

> NOTE: this library is **still in beta** 🚧 but it works perfectly with single protobuf file.
