### ISSUE TITLE
Is there any way to specify any delimiter different than "," in the payload files?

### ISSUE THREAD

**Issue by oscarmullin** [shoreditch-ops/artillery#423]
Hi,

I have a file that's separated by ";" because the "," character is portion of the actual string I need to use.

Is it possible to specify in the payload section of the config, that I would like to use ";" instead of ","?

Thanks

**Comment by mrausch** [comment]
Just discovered a solution to this in another ticket: #278 

> Latest version now includes the ability to pass options in the payload object, which will be passed to csv-parse. Perhaps one of the csv-parse options will allow the proper parsing of your data.

See https://github.com/shoreditch-ops/artillery/issues/278#issuecomment-336567332

Doesn't seem to be in the docs yet.

**Comment by oscarmullin** [comment]
Thanks a lot. I will take a look and provide any feedback here ASAP.
