### ISSUE TITLE
Requests via proxy

### ISSUE THREAD

**Issue by zdmytriv** [shoreditch-ops/artillery#427]
I would like to make requests with artillery via proxy. How do I do that?

I want to do something like this:
```
curl https://httpbin.org/post -kv \
  -x user:password@my-proxy:8080 \
  -H "Content-type: application/json" \
  -d '{"secret": "asdf"}'
```

**Comment by hassy** [comment]
you should be able to set `HTTP_PROXY` / `HTTPS_PROXY` environment variables @zdmytriv

**Comment by hassy** [comment]
Labeling with "docs" as a reminder to add to docs.

**Comment by zdmytriv** [comment]
Actually I have scenario that first POST request goes in one place directly (no proxy) and second POST goes via proxy.
Can I override these env vars in js functions?

**Comment by zdmytriv** [comment]
this hack worked for me:
```
NO_PROXY='example.com' HTTP_PROXY='http://user:password@proxy.com' artillery run config.yml -k
```
set NO_PROXY for one domain and proxy for others. Closing this issue.

**Comment by Alek5andr** [comment]
@hassy,
Do you mean setting up OS environment variables or a test's 'config.environments.variables' section for 'HTTP_PROXY'/'HTTPS_PROXY'?
I'm facing the issue with running artillery in corporate network, behind a proxy.

**Comment by ududsha** [comment]
> @hassy,
> Do you mean setting up OS environment variables or a test's 'config.environments.variables' section for 'HTTP_PROXY'/'HTTPS_PROXY'?
> I'm facing the issue with running artillery in corporate network, behind a proxy.

Did you find any solution? I also have the same issue. For me its giving TIMEOUT for all the requests.
