### ISSUE TITLE
How to send object array from socketio emit

### ISSUE THREAD

**Issue by YenNavisens** [shoreditch-ops/artillery#432]
How do I send object array in socketio emit? I can't find a way to expand variable within yml file.
Something like
```
- function: "generateRandomData"
- emit:
  data: {{objArray}}
```
would be good. 

I use
```
- function: "generateRandomData"
- emit:
  data: "{{objArray}}"
```
But it turned into '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]' string. It's not object anymore.

Any thought?

**Comment by hassy** [comment]
Arrays are not supported yet @YenNavisens.

**Comment by hassy** [comment]
Closing; related issue: #348
