### ISSUE TITLE
 request latency v.s. scenario duration

### ISSUE THREAD

**Issue by TimeInvestor** [shoreditch-ops/artillery#433]
Hi artillery experts,
I just started to use artillery. I am trying to understand what's the difference between request latency and scenario duration?
If I have a very simple test with only one scenario and the scenario only has one simple step, should I expect the data to be same for both request latency and scenario duration (according to my trial run, the data are very different and I cannot make sense of the difference)?
Thanks.

**Comment by hassy** [comment]
It should be about the same, but running a scenario has some overhead (which can also depend on the exact test you're running) so the numbers may diverge slightly. Hope this helps @TimeInvestor

**Comment by TimeInvestor** [comment]
@hassy Thanks for the info.

**Comment by hassy** [comment]
It's the amount of time virtual users take to complete a scenario (which may include one or more requests) @amalhotragannett

**Comment by amalhotragannett** [comment]
Thanks for the help.
