### ISSUE TITLE
afterResponse not triggered in case of connection error

### ISSUE THREAD

**Issue by gerasimos** [shoreditch-ops/artillery#437]
Hello,

I've notice that `afterResponse` is not triggered in case of connection errors (timeouts, invalid host etc) such as `ECONNREFUSED` (on the other hand, such cases are reported in the artillery output).

**Comment by hassy** [comment]
If a connection is refused there's no response to call the function on. :)

**Comment by gerasimos** [comment]
OK, I understand this. In any case, is there any chance to have this in a next release? Or, how else can I (custom) log such cases?

Thank you,
Gerasimos

**Comment by hassy** [comment]
You can use a scenario-level `onError` hook with the following signature:

```javascript
function myOnErrorHandler(err, requestParams, context, events, callback) {
  // ...
  return callback();
}
```

**Comment by gerasimos** [comment]
Thank you, that works for my case.

**Comment by trajano** [comment]
For those who got here, I posted a solution to this in https://stackoverflow.com/questions/71273683/in-artillery-how-do-i-log-etimedout/71332728#71332728
