### ISSUE TITLE
teardown after last request??

### ISSUE THREAD

**Issue by danbambooqualtrics** [shoreditch-ops/artillery#439]
Hello!  So I am looking for a way to run a function after all tests have ran.  I tried using the event emitter and running when `done`, but artillery terminates too early and can't do async within event emitter.  Is there a known way for checking if all tests have run and then run a script?  I don't want to run after each request, and that seems to be all you can do with the 'afterResponse' trigger.  It will work as a clean up api call...

**Comment by hassy** [comment]
The recommended way at the moment is to run post-test logic as a step in a shell script that calls the `artillery` CLI.

It could also be done with a custom plugin (Artillery will wait for a plugin to tell it its done before exiting).

We will be adding support for something like an `afterTest` hook, though there's no ETA on that at the moment.

**Comment by danbambooqualtrics** [comment]
Thanks for your response.  I am trying to go the `plugin` route, but capturing the event `done` does not allow allow async/await functionality within, so can't run teardown when artillery reports it is done.

Looking forward to `afterTest` update.  Thanks.

**Comment by hassy** [comment]
Your plugin class needs to have a `cleanup(callback)`. `cleanup` will be called by Artillery just before it exits, and it'll wait for the callback to be invoked.

**Comment by danbambooqualtrics** [comment]
Perfect!  Problem solved!
