### ISSUE TITLE
artillery-plugin-statsd does not exist

### ISSUE THREAD

**Issue by sericaia** [shoreditch-ops/artillery#44]
Link to https://github.com/shoreditch-ops/artillery-plugin-statsd is placed in [/docs/plugins.md](https://github.com/shoreditch-ops/artillery/blob/master/docs/plugins.md) but artillery-plugin-statsd does not exist. ['minigun-plugin-statsd'](https://github.com/shoreditch-ops/minigun-plugin-statsd) project name must be replaced by 'artillery-plugin-statsd', along with the other plugins.

**Comment by hassy** [comment]
Oops, thanks! Done for the statsd plugin. :ok_hand:
