### ISSUE TITLE
Getting detailed info about status codes in summary

### ISSUE THREAD

**Issue by tylerbhughes** [shoreditch-ops/artillery#443]
I've been working on creating an Artillery script for some endpoints we have on a project at my work. Through the entire script each virtual user will go through and hit 5 endpoints which represents the entire workflow. In my output I end up with a bunch of 401, 404 and 500 status codes. Is there a way I can get more info about the script to know which endpoint(s) caused these problems? Here's the summary output for my script:

```
All virtual users finished
Summary report @ 17:11:48(-0500) 2018-03-19
  Scenarios launched:  180
  Scenarios completed: 108
  Requests completed:  656
  RPS sent: 12.93
  Request latency:
    min: 1
    max: 8090.7
    median: 1336.8
    p95: 6866
    p99: 7780.8
  Scenario counts:
    0: 180 (100%)
  Codes:
    200: 346
    401: 44
    404: 216
    500: 50
```

**Comment by hassy** [comment]
The most flexible option is to write a custom JS function that will log what endpoints (and payloads if needed) caused errors. Another quick option is to run Artillery with `DEBUG=http,http:response` environment variable set to see more details of what's happening.

**Comment by singhasha** [comment]
Can someone have the sample custom JS function for the above issue.

**Comment by roshannair89** [comment]
@hassy could you please share a sample test.yml as well as how you run _DEBUG=http,http:response_ in your terminal as well
I am trying to run my load tests(.yml file) on VS code and seeing this error
![image](https://user-images.githubusercontent.com/89486127/153317030-dcf8aef3-d935-4fdd-8572-6e88301750aa.png)
