### ISSUE TITLE
Having separate variable values for each environment

### ISSUE THREAD

**Issue by tylerbhughes** [shoreditch-ops/artillery#453]
Hi, after reading the docs I know you can set up inline variables through `config.variables` however, is there a way to set it up so I can have a different variable value for each environment?  I thought I had seen somewhere at one point that I could do it like this:

```js
"environments": {
    "dev": {
        "target": "http://devserver.com/api/values",
        "id": "22"
    },
    "test": {
        "target": "http://testserver.com/api/values",
        "id": "43"
    }
}
```

but that doesn't seem to be the case. My end goal is to have these values for each environment then then call them like so `{{ id }}` that way I can pass them as query parameters into my urls. That way all I have to do is specify my environment when I run the script and it will automatically know which id to use. Am I going about this the right way or is there a preferred way to do this?

**Comment by hassy** [comment]
Have you tried setting two different `variables` section under each of the two environments? that should work (and if it doesn't, we'll file it as a bug)

**Comment by tylerbhughes** [comment]
@hassy do you mean like this? 

```js
"environments": {
    "dev": {
        "target": "http://devserver.com/api/values",
        "variables": {
            "id": "22"
        }
    },
    "test": {
        "target": "http://testserver.com/api/values",
        "variables": {
            "id": "43"
        }
    }
}
```

**Comment by tylerbhughes** [comment]
Nevermind, that worked. Thanks!
