### ISSUE TITLE
Document how to escape variables

### ISSUE THREAD

**Issue by gajus** [shoreditch-ops/artillery#454]
```bash
$ artillery run ./venue-events.yaml -v fromDate=2018-01-23,toDate=2018-01-24
Variable definition is not valid. Correct example: "-v key1=value1,key2=value2"
```

I have tried `fromDate="2018-01-23",toDate="2018-01-24"`, etc. but couldn't find a way to make it work.

**Comment by hassy** [comment]
Thanks for creating the issue @gajus. That's a bug, will try to ship a fix soon as it's quite straightforward.
