### ISSUE TITLE
How to perform a match check on status code?

### ISSUE THREAD

**Issue by VeryLazyBoy** [shoreditch-ops/artillery#459]
Is it possible to do a check on status code without custom JS?

**Comment by hassy** [comment]
There's no way to do it with `match` but you it can be done easily with the new expectations plugin:

https://www.npmjs.com/package/artillery-plugin-expect

(The plugin will be bundled into Artillery and replace `match` at some point in the near future.)

**Comment by VeryLazyBoy** [comment]
Thank you!
