### ISSUE TITLE
distributed load testing

### ISSUE THREAD

**Issue by cyberthom** [shoreditch-ops/artillery#47]
Is there support (or planned) for distributed load testing? 

We currently use Locust which handles this quite nicely using master / slave mode:

```
locust -f my_locustfile.py --master
locust -f my_locustfile.py --slave --master-host=192.168.0.14
```

http://docs.locust.io/en/latest/running-locust-distributed.html

**Comment by hassy** [comment]
It's on the roadmap for `v1.4`, coming soon!

**Comment by cyberthom** [comment]
amazing! 🎉🎊🎉🎈

**Comment by alzaltsm** [comment]
Thanks for nice product. Look forward to the "distributed mode".

**Comment by watnotte** [comment]
Any updates on this?  Just perusing my options and we need a distributed solution.  I'd prefer this to JMeter.

**Comment by hassy** [comment]
No ETA for this feature, it hasn't been a high priority since it's easy enough to run multiple instances of Artillery on a cluster of AWS EC2 instances for example. (Not as easy as having the functionality built-in of course, but an acceptable interim solution for a lot of users.)

**Comment by watnotte** [comment]
Ah...okay...that's too bad.  Thanks for the quick response.

**Comment by nonbeing** [comment]
Would really love to have distributed testing features built into Artillery!

@hassy Yes, I could run multiple Artillery processes across a fleet of AWS EC2 instances, but then after the distributed test, I would have to aggregate/summarize metrics like min, max, P95 etc across all the individual JSON files on my own. This is a non-trivial task. Several load-testing tools such as the venerable JMeter (and probably newer ones like Locust) can do this in distributed (master-slave) testing mode. 

I love Artillery for what it can do currently and would really love it more if this feature request could be prioritized :)

**Comment by tvb** [comment]
ETA?

**Comment by hassy** [comment]
The recommended DIY & free way to run a distributed test with Artillery is still to just run it on a number of EC2 instances orchestrated with something like Ansible, or on an ECS/Kubernetes cluster which can be orchestrated with a combination of Docker/Terraform/shell scripting.

Out of the box support for running distributed tests (and more) is also available in [Artillery Pro](https://artillery.io/pro), which is a popular option for teams that would rather not spend the time writing & maintaining in-house automation scripts.

**Comment by ianwalter** [comment]
@hassy Is there any in-between option? Running multiple instances is doable but like mentioned earlier, there isn't an easy to way to aggregate the results from each instance. If Artillery Pro has logic to do this, would I be able to use Artillery Pro outside of AWS?

**Comment by abhayshankar** [comment]
@ianwalter Were you able to achieve this (aggregate reports from each instance) ?
I also have a similar requirement and want to aggregate multiple reports from artillery runs in seperate servers and produce a single HTML report with all the data.
Any help in this regard would be highly appreciated.

**Comment by hassy** [comment]
@ianwalter Artillery Pro is only available on AWS right now, but Kubernetes support is on the roadmap which will make it available in non-AWS environments.

@abhayshankar As a workaround you can configure each Artillery instance to report runtime metrics to a central monitoring system, e.g. Datadog. It won't give you full correct aggregation for e.g. response time distribution but may be close enough depending on your needs.
