### ISSUE TITLE
artillery-plugin-elasticsearch is broken

### ISSUE THREAD

**Issue by KunalSaini** [shoreditch-ops/artillery#470]
There is a npm package [artillery-plugin-elasticsearch](https://www.npmjs.com/package/artillery-plugin-elasticsearch) which when installed has empty index.js file. 

I cannot see the github project for it under https://github.com/shoreditch-ops/ 
Is this plugin supported by you?

**Comment by hassy** [comment]
That was created as a placeholder, sorry about the confusion.
