### ISSUE TITLE
Instance of processor file per virtual user?

### ISSUE THREAD

**Issue by SamFarrington** [shoreditch-ops/artillery#473]
Given the following artillery test spec
```json {
  "config": {
    "target": " ",
    "processor": "./artillery-processor.js",
    "phases": [
      {
        "name": "My Phase",
        "duration": 3,
        "arrivalRate": 3
      }
    ]
  },
  "scenarios": [
    {
      "name": "My Scenario",
      "flow": [
        {
          "function": "pop"
        }
      ]
    }
  ]
}```

And the following processor:

```javascript
let myStack = ['a','b','e','d','e','f','g','h','i', 'j'];

let pop = () => {
   myStack.pop();
   console.log('myStack.length = ${myStack.length}');
}
```

I would expect that the `myStack` array is shared across 3 virtual users, however from my debugging it seems that each virtual user has its own instance of the processor file, meaning that after 3 seconds I have 3 copies of an array containing [`a`,`b`,`e`,`d`,`e`,`f`,`g`] instead of 1 copy of an array containing [`a`]

Is this the behaviour as designed or a bug?

The real use case I have behind this is that I have a dataset that I populate in my processor file that is then used to supply variables for my testing, however the action under test cannot be performed more than once on the same data set, so I need my virtual users to "pop" from the same set to avoid clashes.

I hope I have provided a clear and  thorough enough explanation of this potential issue, however if this is not the case then please don't hesitate to ask for clarification.

**Comment by hassy** [comment]
Unable to reproduce; the expected behavior is that there's only one instance of the processor module, which is shared between all virtual users.

**Comment by SamFarrington** [comment]
Literally just spotted the bug is elsewhere in my code(race condition on the initialise).

My bad and apologies for wasting your time.

**Comment by hassy** [comment]
No worries, glad everything is working!
