### ISSUE TITLE
how is RPS sent calculated

### ISSUE THREAD

**Issue by KunalSaini** [shoreditch-ops/artillery#480]
I have a result from a test run of 60 seconds with arrival rate of 20 , each scenario results in two web requests. 
I don't understand how "RPS sent" is calculated here. Shouldn't it be 40 ( 2400 requests divided by 60 seconds) here. I see 12.63

```
All virtual users finished
Summary report @ 15:52:09(-0500) 2018-05-25
  Scenarios launched:  1200
  Scenarios completed: 78
  Requests completed:  1278
  RPS sent: 12.63
  Request latency:
    min: 1.9
    max: 116499.8
    median: 4892.8
    p95: 9598.2
    p99: 10424.5
  Scenario counts:
    login_and_fetch: 1200 (100%)
  Codes:
    200: 1239
    401: 6
    403: 10
    500: 23
  Errors:
    ESOCKETTIMEDOUT: 1122
```

**Comment by hassy** [comment]
RPS sent is the average of requests processed (ie. for which a response was received), so your test ran averaged 12.63 responses per second in the duration of the test.

More information here: https://artillery.io/docs/getting-started/

**Comment by KunalSaini** [comment]
Thanks for the explanation, so in above example 1278 Requests completed / "X" test duration = 12.63 , so "X" roughly equal to 101 seconds , that's the total duration of test.
