### ISSUE TITLE
error: unknown option `-v' (1.6.10-10)

### ISSUE THREAD

**Issue by lowenthal-jason** [shoreditch-ops/artillery#484]
I'd like to be able to give a variable to artillery from the command line. From the CLI docs, it looks like it should support either `--variables` or `-v`, but when using either option I get this error:

``error: unknown option `-v'``

Output of `artillery -V`
`1.6.0-10`

**Comment by hassy** [comment]
You need a more recent version of Artillery, `v1.6.0-15` is the release that introduced the `-v/--variables` option.

**Comment by lowenthal-jason** [comment]
Thanks. That seems to have been exactly what we needed.
