### ISSUE TITLE
Changing the license to MPLv2

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#49]
Hello, awesome Artillery contributors! (tagged in this Issue)

I have a favor to ask. To help grow the community around this project and to help ensure its long-term success, I'd like to release all future versions of Artillery under the Mozilla Public License v2 (MPLv2).

**Why MPLv2?**

In a nutshell, MPLv2 sits between strong copyleft licenses like GPL and permissive licenses like ISC/MIT and provides the best of both worlds:

- you can use MPLv2-licensed code freely in proprietary projects (In our case, this only relevant if you use `artillery-core` directly, and does not apply to the CLI) or mix it with code under most other open-source licenses
- however, if you make an improvement to MPLv2 licensed code, it generally has to be shared back with the community

MPLv2 is business-friendly, and helps protect the project and its contributors against hostile forks, being re-released as a closed-source product, or patent-related lawsuits.

**Some further reading:**

- [MPLv2 Official FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)
- [The Mozilla Public Licence Version 2 - An Overview](http://oss-watch.ac.uk/resources/mpl2)
- [Mozilla Releases OSI-Approved MPLv2](https://opensource.org/node/594)
- [MPL And Patents](http://en.swpat.org/wiki/MPL_and_patents)

**If you're okay with your contribution to be distributed under MPLv2 going forward, please reply to this thread with a "yes".** :balloon: 

Any questions, please ask away.

Cheers

- [x] @tomgco 
- [x] @Soarez 
- [x] @xicombd 
- [x] @lukebond 
- [x] @cejast 
- [x] @kjgorman 
- [x] @fabiosantoscode 
- [x] @sericaia

**Comment by lukebond** [comment]
yes

(software licences confuse me but from a cursory scan it LGTM)

**Comment by sericaia** [comment]
yes :dancer:

**Comment by Soarez** [comment]
yes

**Comment by xicombd** [comment]
yes :+1:

**Comment by tomgco** [comment]
yes :octopus:

**Comment by kjgorman** [comment]
yes :100:

**Comment by fabiosantoscode** [comment]
Yes :cake: :rainbow: :javascript:

**Comment by cejast** [comment]
yes

**Comment by hassy** [comment]
Thanks everybody :yellow_heart:
