### ISSUE TITLE
CSV doesn't work as expected while using loop

### ISSUE THREAD

**Issue by Sandhyagabbi** [shoreditch-ops/artillery#494]
Here is my script: 
{
  "config": {
    "target": "xxxxxxxxxxxxxxxxxxxxxx",
    "phases": [
      {
        "duration": 60,
        "arrivalCount": 1
      }
    ],
	"processor": "my-function.js",
	"payload": [{
	  "path": "keywords.csv",
	  "fields": ["name", "value"],
      "order": "sequence"	  
	}]
  },
  "scenarios": [
    { 
	  "beforeRequest": ["validDates"],  
      "flow": [
	    {  
		 "loop":[  
         {  
		  "post": {
		    "headers": {
              "Content-Type: "application/json"
            },
            "url": "xxxxxxxxxxx",
            "afterResponse": "logHeaders",
			"json": {
			  "name": "{{name}}",
              "attributes": [
               {
                "name": "myTestAttribute",
                "value": "{{value}}"
               }
             ],
              "validFrom": "{{validFrom}}",
              "validTo": "{{validTo}}"
			}
		  }
		  }
		  ],
		  "count": 10
		}
	  ]  
    }
  ]
}

CSV has values:
name,value
bec843d7-015c-4735-676587j1720,someUniqueBogusTestValue86f68eb0-cc4c-4a4b-a175-456y458301
bec843d7-015c-4735-676587j1721,someUniqueBogusTestValue86f68eb0-cc4c-4a4b-a175-456y458302
bec843d7-015c-4735-676587j1722,someUniqueBogusTestValue86f68eb0-cc4c-4a4b-a175-456y458303

When the test is run, only the first value is getting picked from the csv file for all the requests.

**Comment by hassy** [comment]
@Sandhyagabbi that's expected behavior - the values loaded from the CSV file are set once per virtual user, so they will remain the same when that user executes the loop.

**Comment by Sandhyagabbi** [comment]
@hassy thank you for the quick response. My requirement is that the name should be unique for every request else the service throws an error. I would try and see if I can achieve it using custom java script.

**Comment by halilyuce** [comment]
@Sandhyagabbi @hassy I have the same issue, how did you solve it? I want to use unique rows in CSV per virtual user.

You can see my config here : https://github.com/artilleryio/artillery/issues/60#issuecomment-987795866
