### ISSUE TITLE
Cannot use variables with hyphenated values through -v option

### ISSUE THREAD

**Issue by JohnDoePBabu** [shoreditch-ops/artillery#498]
I noticed that the regular expression validating CLI variables ```/^([A-Za-z_][\w\d]*=[\w\d]+)(,[A-Za-z_][\w\d]*=[\w\d]+)*$/``` does not allow values with hyphens, e.g: c033fe8e-845d-4f9f.
Was this specifically avoided or are you open to PR including the hyphen in the regex?

**Comment by hassy** [comment]
This no longer applies, since the extra variables are now passed in as JSON. :)
