### ISSUE TITLE
SSL Certificate support in artillery : Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by vijay-nts** [shoreditch-ops/artillery#502]
I am using  "artillery-plugin-http-ssl" module for loading certificates. When i run the tests I am getting "Error: error:0906D06C:PEM routines:PEM_read_bio:no start line" . 

  tls:
    cert: "keystore-pcc-prod-app.cer"
    passphrase: "****"
  plugins:
    http-ssl: {}

Is there any other way to run the tests? It's working fine with the same certificate in SOAP UI. Anything I am missing? Pls help

**Comment by hassy** [comment]
That's not one of the official Artillery plugins, I suggest asking in the relevant support channel for the plugin.

**Comment by vijay-nts** [comment]
Thank You..I know we have plugin available for artillery pro but is there any plugin available for artillery  to handle this requirement? Pls help

**Comment by hassy** [comment]
We are unable to provide support for third-party plugins here, sorry. I'd suggest investigating what "PEM routines:PEM_read_bio:no start line" might mean, it sounds like an issue with the format of the certificate.
