### ISSUE TITLE
Resolve the JSONPath conflict

### ISSUE THREAD

**Issue by yusuf-kami** [shoreditch-ops/artillery#506]
The currently released version of [Artillery](https://www.npmjs.com/package/artillery) (^1.6.0-22) uses the old version of [JSONPath](https://www.npmjs.com/package/JSONPath) (version "^0.11.2")) as a dev dependency. But we should all be aware by now that there is a know conflict between this package and the newer more up-to-date [jsonpath](https://www.npmjs.com/package/jsonpath) (version "1.0.0") package. If another dependency is using the jonspath module as well as Artillery there will always be a conflict between the two jsonpath packages.

**Suggestion**
We suggest [Artillery](https://www.npmjs.com/package/artillery) move to either using the [jsonpath](https://www.npmjs.com/package/jsonpath) package or the [jsonpath-plus](https://www.npmjs.com/package/jsonpath-plus) package so as not to cause conflicts in repositories that utilize the [jsonpath](https://www.npmjs.com/package/jsonpath) package.

**Reccommendation**
I recommend actually using [jsonpath](https://www.npmjs.com/package/jsonpath) package and move off of [JSONPath](https://www.npmjs.com/package/JSONPath) completely.

**Comment by skalfyfan** [comment]
Am currently running into this exact same issue!

**Comment by hassy** [comment]
Thanks @yusuf-kami!

**Comment by skalfyfan** [comment]
@hassy do we know when next release may be? 
I took a look for a development branch and can't find one 😢

**Comment by hassy** [comment]
@skalfyfan There will be a release in the next week or two.

We don't use development branches on Artillery, all work happens in forks.
