### ISSUE TITLE
How can use --override to override only the loop count value?

### ISSUE THREAD

**Issue by Balaji1294** [shoreditch-ops/artillery#528]
Hi,

Is there a way I can override the loop count value using --overrides?

Thanks in advance!!

**Comment by hassy** [comment]
`--overrides` can only be used to override the `config` section of your test script. You could define an [inline variable](https://artillery.io/docs/script-reference/#inline-variables) and override that.

**Comment by Balaji1294** [comment]
Hi Hassy,

variables:
    loopcount: 
      - 10

is this right?

**Comment by Balaji1294** [comment]
I tried as you suggested. I dont think we are able to assign value to count as {{ anyname }}.

I tried the inline variable within my request payload and it worked as expected.

It would be great if you could try it and help me out.

**Comment by hassy** [comment]
It is possible to use a variable for `count`, make sure you're on the latest version of Artillery.

**Comment by Balaji1294** [comment]
I am on the latest version.

When I use count : {{ loopcount }}, following is my output.
 
Started phase 0, duration: 1s @ 15:15:39(+0530) 2018-08-28
Report @ 15:15:41(+0530) 2018-08-28
  Scenarios launched:  1
  Scenarios completed: 1
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN

All virtual users finished
Summary report @ 15:15:41(+0530) 2018-08-28
  Scenarios launched:  1
  Scenarios completed: 1
  Requests completed:  0
  RPS sent: NaN
  Request latency:
    min: NaN
    max: NaN
    median: NaN
    p95: NaN
    p99: NaN
  Scenario counts:
    Name : 1 (100%)

**Comment by Balaji1294** [comment]
Hey Hassy,

It worked for me.. the issue was I had to use the inline variable as count: "{{ loopcount }}". But I had used it has count: {{ loopcount }}.

Thanks for the help!!
