### ISSUE TITLE
loop not working

### ISSUE THREAD

**Issue by cyberthom** [shoreditch-ops/artillery#53]
I am trying to get a `loop` step to work but am getting the following exception:
```
/node_modules/artillery/node_modules/artillery-core/lib/engine_util.js:44
    let match = o.match(funcCallRegex);
                 ^

TypeError: Cannot read property 'match' of undefined
    at template (/node_modules/artillery/node_modules/artillery-core/lib/engine_util.js:44:18)
    at f (/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:26:32)
    at fn (/node_modules/artillery/node_modules/async/lib/async.js:746:34)
    at /node_modules/artillery/node_modules/async/lib/async.js:1213:16
    at /node_modules/artillery/node_modules/async/lib/async.js:166:37
    at /node_modules/artillery/node_modules/async/lib/async.js:706:43
    at /node_modules/artillery/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/node_modules/artillery/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

I have literally tried the example file from your unit tests folder to make sure there's no syntax error: https://github.com/shoreditch-ops/artillery-core/blob/master/test/scripts/loop.json

Findings:

The `step` function (in engine_http.js) tries to pass `params.url` to the `template` function (in engine_util.js). However `params.url` is `undefined` in the case of loops as they are arrays, not objects: `[ { get: { url: '/' } } ]`

Am I doing something wrong? Has `loop` been fully implemented yet or should loop be an object with a single step rather than an array with a list of steps?

**Comment by hassy** [comment]
The example should work - it might be that `artillery-core` that's installed on your machine is not the most recent one. Could you try reinstalling `artillery` and trying again?

**Comment by cyberthom** [comment]
Ah, good call - I was on artillery 1.3.2. 
1.3.4 works fine 👍🏻
