### ISSUE TITLE
Setting output file name

### ISSUE THREAD

**Issue by sw360cab** [shoreditch-ops/artillery#55]
Trying figuring out how I can provide a filename in .json config files for the output file generated in reports

I've found in src files this:
**lib/commands/run.js**

    const defaultOptions = require('rc')('artillery');
    ...
    if (defaultOptions.output) {
      logfile = moment().format(defaultOptions.output);
    } else {
      logfile = moment().format('[artillery_report_]YMMDD_HHmmSS[.json]');
    }

How can i set this?
Is this usable from config file?

**Comment by hassy** [comment]
@sw360cab you can use the `-o` flag to set the name of the file, e.g.:

`artillery run -o output.json mytest.json`

**Comment by sw360cab** [comment]
Works smootly! 
Sorry for bothering, but I really cannot find that on the documentation...

Thanks a lot

**Comment by hassy** [comment]
No worries. The docs are a major priority for the next release.

**Comment by shikha0981** [comment]
Hi @hassy ,

Is there a possibility to get a detailed information about what the "Latencies" mean under intermediate report in the artillery report  json file.

Basically what does it decipher ? 

I have a requirement where i need to fetch scenarios completed per 1 second ( load per sec )by artillery
