### ISSUE TITLE
TypeError: task is not a function

### ISSUE THREAD

**Issue by dugouchet** [shoreditch-ops/artillery#553]
during my scenario est running, I have this error : 
```
/.nvm/versions/node/v8.9.1/lib/node_modules/artillery/node_modules/async/lib/async.js:718
            task(_restParam(function (err, args) {
            ^

TypeError: task is not a function
```
my artillery version is : 1.6.0-24 with node 8.9.1

**Comment by hassy** [comment]
This is most likely to do with a typo or indentation issue in the test script, could you post that?

**Comment by dugouchet** [comment]
caused by my scenario

**Comment by squiz8** [comment]
I have a similar error while working with async.parallel
task(_restParam(function (err, args) {
            ^

TypeError: task is not a function
