### ISSUE TITLE
Docs for disabling HTTP TLS verification are wrong

### ISSUE THREAD

**Issue by alexmuller** [shoreditch-ops/artillery#554]
Hi there! I can't find the docs source online anywhere so just opening an issue here.

On https://artillery.io/docs/http-reference/ it says that `config.http.tls.rejectUnauthorized` should be set to `false`. However I don't think this works as the code checks for `config.tls.rejectUnauthorized`.

Thanks!

**Comment by hassy** [comment]
Thanks @alexmuller, fixed - https://artillery.io/docs/http-reference/#tlsssl

**Comment by alexmuller** [comment]
Thank you! :)
