### ISSUE TITLE
Node 4/5 is no longer compatible

### ISSUE THREAD

**Issue by ryanwholey** [shoreditch-ops/artillery#558]
Apologies if this should be filed elsewhere, as the document I'm referring to isn't part of this repo.
The [getting started](https://artillery.io/docs/getting-started/) docs say

```We recommend Node 7 for running Artillery, but any version above 4 will work.```

however, there have been [commits](https://github.com/shoreditch-ops/artillery/pull/430/files) that include destructuring and the rest/spread operator which [isn't supported until node 6](https://node.green/).

It would be great to update the getting started doc to reflect the current supported version (node 6?). If the repo is public I'm happy to make a pr there. Thanks!

**Comment by hassy** [comment]
Thanks @ryanwholey! The docs have been updated.
