### ISSUE TITLE
Nested loop does not execute

### ISSUE THREAD

**Issue by toxtox7** [shoreditch-ops/artillery#559]
>         - loop:
>          - emit:
>              channel: "test channel 1"
>              data: "12345"
>          - think: 5
>          - loop: 
>              - emit:
>                 channel: "test channel 2"
>                 data: "I am here now"
>              - think: 5
>              count: 5
>          count: 25

It's my understanding from previous issues (https://github.com/shoreditch-ops/artillery/pull/476, https://github.com/shoreditch-ops/artillery/issues/219) that nested loops are support.
However the code above does not emit anything to the server. Not the emit from the outer loop and not the emit from the inner loop.

**Comment by hassy** [comment]
Looks like a bug specific to the Socket.io engine - to be fixed in the upcoming release. Thanks for the bug report @toxtox7!
