### ISSUE TITLE
Any way to specify timeout?

### ISSUE THREAD

**Issue by robertherber** [shoreditch-ops/artillery#56]
Is there any possibility to specify a longer timeout than 10s, which seems to be the current limit? Our server (and third-party services behind it) does some heavy lifting with payments etc and 10s doesn't quite cover it for us.

**Comment by hassy** [comment]
@robertherber yes, you can set `config.timeout` to override the default 10 seconds. It wasn't documented, but it is now - https://github.com/shoreditch-ops/artillery/wiki/Reference#config - thanks!

**Comment by robertherber** [comment]
Thanks for a quick response, I appreciate it!
