### ISSUE TITLE
Provides artillery.run results

### ISSUE THREAD

**Issue by YLeight** [shoreditch-ops/artillery#567]
When run artillery inside module, it would be great to recieve running results (either with callback, promise or [event emitter](https://github.com/shoreditch-ops/artillery/issues/173#issuecomment-259528870)).

Possible using
```javascript
// ...
try {
  const stats = await artillery.run(config, options);
  // ...
} catch (e) {
// ...
```

**Comment by hassy** [comment]
hi @YLeight - we've had a couple of similar discussions before in this project. The current thinking is that we don't want to encourage the use of Artillery as a library from other Node.js modules, instead preferring to focus on making standard Unixy ways to interop better and easier to use.
