### ISSUE TITLE
Maximum throughput for https

### ISSUE THREAD

**Issue by brianmars7** [shoreditch-ops/artillery#568]
I am currently using the command:

artillery quick --count 9999999 -n 999999 -k https://internalhost/

I expect that it would send as much traffic as the host can, but when I look at wireshark, it shows I am sending 114 Mbit per second. 

"Top" on both server and client shows free cpu, memory and iops. I user iperf3 to test bandwidth, and I have full gigabit to my server (it's one room over).

Why would the average throughput be this low on artillery? How can I increase it?

**Comment by hassy** [comment]
Yeah, Artillery won't be able to match the numbers you're seeing with iperf - there's a lot more happening behind the scenes than just pushing bytes across a TCP connection, e.g. distinct sockets are created for different virtual users, setting up SSL connections, HTTP parsing etc. Plus the actual payload of each request is tiny (it's only a simple GET).
