### ISSUE TITLE
Indefinite loop does not work

### ISSUE THREAD

**Issue by facboy** [shoreditch-ops/artillery#57]
I might be configuring this wrong, but if I configure a loop and omit the 'count' variable to have the loop repeat indefinitely, requests gets reported as 0 and no stats are recorded for request latency.  If I add the count variable then things seem to work as expected

**Comment by hassy** [comment]
Nope, you're not wrong - it's a bug.

**Comment by hassy** [comment]
Fixed in `1.3.5`, `npm install -g artilery@latest` to upgrade. :)
