### ISSUE TITLE
Capture socket.io acknowledgement response 

### ISSUE THREAD

**Issue by HosseinAgha** [shoreditch-ops/artillery#572]
It would be awesome if we could also capture [socket.io acknowledgement response](https://socket.io/docs/#Sending-and-getting-data-acknowledgements) instead of waiting for a response on a channel.   
We could use a boolean option like `captureAck`.  
I'd be happy to contribute if you're OK with that.

**Comment by HosseinAgha** [comment]
I just read the code and found out you have an acknowledge option on `spec.emit` but it is not documented.  
How can we contribute to documentation? I could not find a github pages branch or a docs project.

**Comment by hassy** [comment]
The docs aren't public (yet), but hopefully will be soon. Thanks for the offer to send a PR in! I'll update the docs with `acknowledge` ASAP.

**Comment by hassy** [comment]
Docs have been updated: https://artillery.io/docs/socketio-reference/#acknowledgements-response-validation Thanks @HosseinAgha!

**Comment by SHwan93** [comment]
@hassy  can capture ack data? and reuse subemit?

**Comment by eliezercazares** [comment]
> Docs have been updated: https://artillery.io/docs/socketio-reference/#acknowledgements-response-validation Thanks @HosseinAgha!

It's gone :( I'm still in the quest to listen an emit back from server during testing
