### ISSUE TITLE
Cheerio pick a random node matching the selector

### ISSUE THREAD

**Issue by matthisk** [shoreditch-ops/artillery#573]
I would like the Cheerio selector to pick a random node matching my selector, is this possible? The docs do not seem to mention this type of behavior. But say I have a page with 5 links, each link element's class name starts with `hello` the selector `a[class^=hello]` would select all 5 nodes, but Artillery will always pick the `href` attribute of the first node. I want each virtual user to pick the href attribute from a random node matching the selector.

**Comment by hassy** [comment]
@matthisk thanks for opening the issue! The functionality is there already, but it wasn't documented. Deploying an update to docs right now.

**Comment by hassy** [comment]
and the update is live: https://artillery.io/docs/http-reference/#extracting-and-reusing-parts-of-a-response-request-chaining
