### ISSUE TITLE
Using scenario flow `function` without `get` or `post` returns NaN for all latency measurements

### ISSUE THREAD

**Issue by seanconklin** [shoreditch-ops/artillery#578]
Instead of sending a GET or POST request with one of my artillery.io test scenarios, I am solely running a `function` call in an external JS file. That external JS uses the [Puppeteer project](https://github.com/GoogleChrome/puppeteer) to run a headless Chromium browser and run its own test flows synthetically. It runs fine using artillery.io as the load engine, but artillery.io does not count the response times. Only the scenario and request counts work.

Is there a way to count response time (latency) from an external script? Perhaps calculate it using JS and throw that back to artillery.io to include in the report? Or just make my own collectors and report? Curious if anybody has any tips or if there is agreement that `function` should be counted as latency.

[External JS test script](https://github.com/Coded-Commerce-LLC/WooCommerce-Load-Test/blob/master/loadtest_synthetic.js) (puppeteer)

To install puppeteer globally with Node, use `sudo npm install -g puppeteer`

[YAML configuration](https://github.com/Coded-Commerce-LLC/WooCommerce-Load-Test/blob/master/loadtest_synthetic.yml) (artillery.io)

To run the test, use `artillery run loadtest_synthetic.yml -o results.json`

**Comment by hassy** [comment]
Interesting use case @seanconklin! `function` calls do not count as latency (since they could be doing any amount of work, and not necessarily making any HTTP request). You can use custom metric support to create your own latency metrics though:

```javascript
function myCustomFunction(context, events, done) {
  events.emit('histogram', 'someEndpointLatency', 123);
  return done();
}
```

This will create a custom metric called `someEndpointLatency` of type `histogram` (ie you'll get min/max/p95/p99 distribution for it), which will be displayed in the console output and the HTML report.

**Comment by seanconklin** [comment]
Thanks @hassy! That suggestion does work nicely. The report provides a useful graph, so artillery.io serves as a load engine and a reporting engine even with the external test flow. Thanks for the tip, and I will commit this to the project referenced above for anybody else looking for the full code sample.

**Comment by benel** [comment]
Hi @seanconklin,

I also try getting Artillery call Puppeteer. 

> External JS test script (puppeteer)

I'm afraid your link is broken. Would you accept sharing a part of your script ?
A minimal sample would be enough: it is mainly to ckeck the `require` parts, and the way to launch and close puppeteer without memory leaks.

Regards.

**Comment by benel** [comment]
> I'm afraid your link is broken. 

Sorry for the inconvenience. [I've found it](https://github.com/Coded-Commerce-LLC/WooCommerce-Load-Test/blob/master/synthetic/loadtest_synthetic.js). It was still there but with a different path.
