### ISSUE TITLE
TLS certificate verification doesn't always work as expected

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#59]
Artillery does not always recognize valid TLS certificates. For example:

```
$ artillery quick -d 10 -r 5 https://artillery.io

  Scenarios launched: 49
  Scenarios completed: 0
  Number of requests made: 0
  RPS: 4.73
  Request latency:
    min: Infinity
    max: -Infinity
    median: NaN
    p95: NaN
    p99: NaN
  Scenario duration:
    min: Infinity
    max: -Infinity
    median: NaN
    p95: NaN
    p99: NaN
  Errors:
    UNABLE_TO_VERIFY_LEAF_SIGNATURE: 49
```

The issue is that Node.js uses its own certificate bundle, which does not include many CAs. To fix, a custom bundle needs to be used by the HTTP engine.

**Comment by vineyugave** [comment]
@hassy   How do we point to the custom HTTP engine ?

**Comment by hassy** [comment]
Not sure what you mean @vineyugave. If you want to use a custom engine, you need to set the `engine` field of your script to the $name of the engine, and have `artillery-engine-$name` available to `require`.

**Comment by vineyugave** [comment]
@hassy I just wanted to know how you overcame this issue where it gives "UNABLE_TO_VERIFY_LEAF_SIGNATURE: 49" error...

**Comment by hassy** [comment]
@vineyugave you can use `-k` flag to turn off certificate validation, like so: `artillery run -k myscript.json`

**Comment by vineyugave** [comment]
@hassy thanks a ton.. that saved my day ...

**Comment by alex7kir** [comment]
Hi, I have a problem with this option. I've tried using every variant of turning certificate validation off described [here](https://artillery.io/docs/testing_http.html#ssl), but UNABLE_TO_VERIFY_LEAF_SIGNATURE error still appears. What could the problem be?

**Comment by hassy** [comment]
@alex7kir Odd! Is it a self-signed certificate? Are you testing HTTP or
WS/Socket.io?

**Comment by alex7kir** [comment]
@hassy Yes, it is a self-signed certificate. I'm testing WS.

**Comment by hassy** [comment]
@alex7kir thanks, that's a bug - will ship a fix soon

**Comment by hassy** [comment]
@zavermax yes that's a known problem (described in the issue) caused by Node.js having its own CA store. Which CA issued the cert that isn't being recognized?

**Comment by zavermax** [comment]
Comodo

**Comment by hassy** [comment]
Closing this for now as more recent versions of Node seem to include more CAs.
