### ISSUE TITLE
Pick rows from CSV in sequence rather than at random?

### ISSUE THREAD

**Issue by markgandy** [shoreditch-ops/artillery#60]
Each scenario in my test needs to have a unique orderNumber variable.  My orderNumbers are read in from CSV file, but because these are picked at random the same orderNumber can (and does) get re-used. Is there any way that variables from CSV can be looped through in sequence rather than picked at random?

**Comment by hassy** [comment]
@markgandy there's no way to do that at the moment. Adding an option to read the rows in sequence shouldn't be much work though.

For your use-case, once the last row is reached, would it be okay to wrap around and start from row 0 again?

Do these order numbers correspond to some pre-existing id on the backend, or would it work if you could create them in the scenario on the fly?

**Comment by markgandy** [comment]
@hassy Yes wrapping and starting from row 0 again would be fine. The order numbers do need to match against our backend. Orders need to be imported in a batch before the test runs (via API call), so we're currently doing that as a separate step before the test runs. Would be nice to do this in artillery with a before test hook, but I don't think that is supported..(and I'm getting off track for this issue).

I'm happy to look at creating a pull request for reading the rows in sequence if you can point me in the right direction?

**Comment by hassy** [comment]
> I'm happy to look at creating a pull request for reading the rows in sequence if you can point me in the right direction?

That would be great. The place to start is [runner.js#330](https://github.com/shoreditch-ops/artillery-core/blob/master/lib/runner.js#L330). That's where a random row is being picked from each payload file (there can be more than one) - so we'd just need to keep an index per payload.

To control the behavior, I suggest we add an option to payload definitons:

```javascript
{
  "config": {
    "payload": [
      {
        "path": "./orders.csv",
        "fields": ["orderId", "someOtherField"],
        "order": "iterate" // or "random" which the default setting
      }
    ]
  }
  // rest of the script
}
```

Then inside `createContext` what `"order"` is set to.

Let me know what you think

**Comment by markgandy** [comment]
@hassy see this commit (https://github.com/markgandy/artillery-core/commit/21bcdefc18af011e54b8699be68ce74ed846e6a3) hopefully this is ok. Just trying to figure out how to test the sequencing then will open pull request. Let me know if you have any tips..

**Comment by hassy** [comment]
That looks good. For testing, I'm thinking we should extract the logic into its own function that can be tested in isolation, e.g. define something like:

```javascript
function createOrderedReader(data) {
  let i = 0;

  return function() {
    let result = data[i];
    if (i < data.length - 1) {
      i++
    } else {
      i = 0;
    }
    return result;
  }
}
```

And then create a "reader" for each payload that specifies `order = 'iterate'` and call it in `createContext`.

Another though - `iterate` perhaps isn't a great name, maybe we should go with something like `sequence`?  open to suggestions on this one!

**Comment by hassy** [comment]
Picking elements at random will need to be extracted into its own function too - I can do that, or if you don't mind you can make that part of your PR.

**Comment by markgandy** [comment]
Nice idea for creating readers @hassy. It does look cleaner.  I've opened a PR here - https://github.com/shoreditch-ops/artillery-core/pull/42

**Comment by markgandy** [comment]
@hassy thanks for merging - when will new version with this change get published to npm?

**Comment by hassy** [comment]
@markgandy Just published `artillery@1.3.7`. Thanks for the PR!

**Comment by markgandy** [comment]
Thanks - it's working nicely!

**Comment by halilyuce** [comment]
I have the same issue, each id must be unique but it picked randomly. How can use every row uniquely? I tried sequence and iterate as the value of order but both have the same result, unfortunately. @hassy @markgandy 

```
config:
  target: "wss://eu-w2.ceclients.cardeasy.com"
  processor: "./my-functions.js"
  phases:
    - duration: 5
      arrivalCount: 10
      name: Warm up
  payload:
    path: "epids.csv"
    fields:
      - "epid"
    order: iterate

scenarios:
  - engine: ws
    flow:
      - connect:
          function: "connectHandler"
      - log: "{{ epid }}"
```
