### ISSUE TITLE
Request and Response Should Print in Pairs

### ISSUE THREAD

**Issue by jamesvandyne** [shoreditch-ops/artillery#63]
Run a test with DEBUG=http,http:response together.

Results: We print a list of requests and then a list of responses.

Expected Behavior: We should print the request and subsequent response together so it's easier to match up our response to our request .

**Comment by hassy** [comment]
@jamesvandyne Thanks! :+1: 

If you want to take a stab at it, the place to fix it is `engine_http.js`:
1. [103](https://github.com/shoreditch-ops/artillery-core/blob/master/lib/engine_http.js#L103)
2. [114-115](https://github.com/shoreditch-ops/artillery-core/blob/master/lib/engine_http.js#L114-L115)

(Perhaps formatted with `JSON.stringify` to make the output easier to read.)

**Comment by jamesvandyne** [comment]
Added with pull request #[43](https://github.com/shoreditch-ops/artillery-core/pull/43) in artillery core
