### ISSUE TITLE
Write html report to file, don't open. For CI

### ISSUE THREAD

**Issue by antony** [shoreditch-ops/artillery#65]
Something that I want to do is just make the html file available for downloading from my CI environment, and not try to open it in a browser.

Opening the browser means my build never ends, and fails.

I propose passing -o/--output to the report command, as with the run command, and if specified, output to  a file and don't try to open the report.

**Comment by himasimplisafe** [comment]
What is the command for not opening browser when report generated

**Comment by bcexopolllo** [comment]
> What is the command for not opening browser when report generated
according to commit https://github.com/artilleryio/artillery/commit/aa971256d7d3e707099188296a1790cf51adcaec:
when you add additional param -o like here:
```artillery report .\Reports\testResults.json -o .\Reports\TestResults.html```
will not open browser by default
