### ISSUE TITLE
Re-add test coverage reports

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#69]
A few rather embarrassing bugs have been shipped in the last couple of months which could have been avoided with more rigorous testing. Test coverage used to be at 90%+ but it isn't anymore.

To help prevent shipping more bugs in the future we should:
- [ ] Enable test coverage reports
- [ ] Fail builds if coverage is <80%

**Comment by hassy** [comment]
https://codecov.io looks nice

**Comment by mikefeher-waitr** [comment]
How do you feel about a build tool like [Grunt](http://gruntjs.com/)? They have a few good enforcers out in the wild. [grunt-code-coverage-enforcer](https://github.com/tapasvimoturu/grunt-code-coverage-enforcer) [grunt-codecov.io](https://github.com/r3b/grunt-codecov.io). I also like throwing [Code Climate](https://codeclimate.com) into the mix for static analysis but it doesn't support the fancy Coverage in PRs

**Comment by hassy** [comment]
Don't need Grunt for this, Istanbul already produces coverage reports - we just need to be able to send them off somewhere like codecov.io to be able to display coverage stats continuously.

We should consider Code Climate too 👍

**Comment by mikefeher-waitr** [comment]
@hassy Looks like there is something going on with the tests for latest [build 104](https://travis-ci.org/shoreditch-ops/artillery) from PR #104 and I'm getting the same error locally. Not familiar enough with Bats to dive into it at the moment. I'll throw in a coverage checker once we get a green build

**Comment by hassy** [comment]
@mikefeher-waitr looks like an issue with line endings, I'll take a look

**Comment by hassy** [comment]
@mikefeher-waitr that's been fixed now

**Comment by mikefeher-waitr** [comment]
@hassy Thanks! I'll see if I can get that patched at lunch. Cheers! :beers:
