### ISSUE TITLE
CSVs don't appear to work

### ISSUE THREAD

**Issue by antony** [shoreditch-ops/artillery#72]
I realise there is a test for this that seems to pass, but given my CSV:

```
abcde,Mita,20554,Novick,Septfontaines,1111,asnyder0@dagondesign.com,Tinactin,Andrea Snyder,asnyder0@wp.com
1243fsdfs,Browsezoom,385,Logan,Malkā,4444,levans1@51.la,SORE MUSCLE AND JOINT PAIN RELIEF,Lawrence Evans,levans1@desdev.cn
gdfgdfg,Flashset,9451,Sage,Amarillo,79165,ebell2@desdev.cn,Morphine Sulfate,Eugene Bell,ebell2@blog.com
```

and my config block:

```
    "payload": {
      "path": "./data2.csv",
      "fields": ["registration","name","building","street","city","postcode","email","branch","fullName","fullEmail"]
    }
```

My request is:

```
  {
          "loop": [
            {
              "post": {
                "url": "/v1/xxyyzz/abcde",
                "json": {
                	"registration": "{{ registration }}",
                	"name": "{{ name }}",
                	"contact": {
                		"address": {
                			"building": "{{ building }}",
                			"street": "{{ street }}",
                			"line1": "1th 4th",
                			"city": "{{ city }}",
                			"postCode": "1234",
                			"country": "DK"
                		},
                		"phoneNumber": "12345678",
                		"email": "{{ email }}"
                	}
                },
                "capture": {
                  "json": "$._id",
                  "as": "someId"
                }
              }
            }
          ],
          "count": 1
        }
```

I'm having no luck at all - unfortunately I can't see a way to get good debug information about the requests i'm sending (http:request would be nice) but my API is telling me that 'registration' is blank each time, and if I hardcode it, the next entry is blank, and so on.

**Comment by hassy** [comment]
Thanks for the bug report! This is a known bug, for now the workaround is to wrap the payload definition in an array like this:

```
    "payload": [{
      "path": "./data2.csv",
      "fields": ["registration","name","building","street","city","postcode","email","branch","fullName","fullEmail"]
    }]
```

**Comment by hassy** [comment]
This is the offending line btw if you want to take a stab at it:

https://github.com/shoreditch-ops/artillery/blob/master/lib/commands/run.js#L105-L107

`options.payload` is the path to the payload file passed in via the `-p` flag. The code needs to take into account that `options.payload` might be undefined but the payload definition may have the `"path"` attribute set.

**Comment by antony** [comment]
Ah - I'll try this, thanks.

I've actually had an idea for the CSV functionality, but I'll raise it in another issue to discuss.
