### ISSUE TITLE
Need help in understanding the output

### ISSUE THREAD

**Issue by ashwanikumar04** [shoreditch-ops/artillery#80]
Hello:

I am trying to user Artillery to load test my node application. I am running Artillery on my development machine hence can see the logs which are generated when even any api call is made from other application. 

This is output which I get from after running artillery on my app
```
  Scenarios launched: 26070
  Scenarios completed: 78
  Number of requests made: 78
  RPS: 82.18
  Request latency:
    min: 414.9
    max: 9809.6
    median: 3550.8
    p95: 9245.4
    p99: 9755.3
  Scenario duration:
    min: 442.3
    max: 9812
    median: 3554.5
    p95: 9249.3
    p99: 9757.6
  Codes:
    200: 78
  Errors:
    ETIMEDOUT: 9412
    ESOCKETTIMEDOUT: 30
    ECONNREFUSED: 16550
```
Clearly there are Huge number of ETIMEDOUT and ECONNREFUESED count. While in the log I do not see any errors. 
If It helps this is my json file
```
{
	"config": {
		"target": "http://localhost:8090/api/v1",
		"phases": [{
			"duration": 60,
			"arrivalRate": 5,
			"rampTo": 10
		}, {
			"duration": 120,
			"arrivalRate": 10,
			"rampTo": 50
		}, {
			"duration": 120,
			"arrivalRate": 5,
			"rampTo": 500
		}]

	},
	"scenarios": [{
		"name": "Test",
		"flow": [{
			"post": {
				"url": "/users/",
				"json": {
					"name": "test"
				},
				"capture": {
					"json": "$.data.id",
					"as": "id"
				}
			}
		}]
	}]
}
```
I am not sure what I am doing wrong. Any idea what can be wrong?

**Comment by hassy** [comment]
These are OS level errors (sockets connections timing out) which you wouldn't see in your application logs.

You're opening *a lot* of TCP connections (every arrival is a separate TCP connection) and may be running out of file descriptors. I'd start by increasing the limit - this depends on the OS, on Linux you'd use a combination of `ulimit` and settings in `/etc/sysctl.conf`. `netstat` is also useful to monitor the number of open connections.

**Comment by ashwanikumar04** [comment]
Thanks,
How to do this on windows. I am on windows for development.

**Comment by hassy** [comment]
I don't know.

**Comment by sheltonpaul89** [comment]
Is this a problem with the application server or the load test controller (where artillery is installed)?

**Comment by hassy** [comment]
@sheltonpaul89 more likely to be the server in OP's case, but it's always a good idea to tune the load-generating host too.
