### ISSUE TITLE
Is there a way to capture the response headers (like ones used for Authentication)

### ISSUE THREAD

**Issue by venkatesh-tr** [shoreditch-ops/artillery#82]
I am using a header to pass on JWT token which is used for authenticating/authorizing the application user. When user authenticates first providing his credentials, he will get a JWT token created and sent using a header to client. This header has to be captured and stored as a variable.

This token has to be sent to server on subsequent requests. As per my understanding looking at the code, this is not possible as of now!. Can somebody provide me insights into feasibility of this problem? Or something to work as a work around? 

**Note:** I see that there is a afterResponse method callback which I can register to get the response in callback. I can use it, but I don't know how to store a variable from third party callback into artillery context.

**Comment by hassy** [comment]
Hi @venkatesh-tr, you should be able to use the `afterResponse` hook. The function that's called takes 4 arguments, the third of which is the context for that virtual user.

The `context` parameter has a `vars` attribute, which is an object where keys are the names of the variables and the values are their values.

So you'd do something like:

```
function getToken(request, response, context, ee) {
  var token = response.headers['x-my-token'];
  context.vars['authToken'] = token;
}
```

And then use `authToken` in subsequent request like any other variable.

(This feature is very experimental by the way and is likely to change, but it should work for you for now.)

**Comment by venkatesh-tr** [comment]
I guessed it correctly then... But how can I configure this function using json config file that I am creating? 

Is there any tests/samples which can illustrate this?

**Comment by venkatesh-tr** [comment]
I got it by looking at the code: I have to pass the processor as a config parameter which is a script name which can be loaded with respect to current script directory.

It is working fine. Thanks..

**Comment by venkatesh-tr** [comment]
Even though it is working fine as of now using afterResponse, I wish to see this as a feature with documentation soon. I like this framework now and using it rigorously. So let me know if I can contribute some documentation about this afterResponse parameter.

**Comment by hassy** [comment]
@venkatesh-tr glad to hear it's working well for you! 👍 It's still too early to document this feature - it's not even comprehensive yet (e.g. no `preRequest` hook implementation, no support at all in the WebSocket engine). It **will not** be removed, so you don't need to worry about relying on it, however the interface might change slightly to make it easier to use and more versatile, but not in a major way. When we're ready, it would be great to have doc / tutorial contributions, thanks for offering!
