### ISSUE TITLE
Scraping of console debug output doesn't seem to be supported

### ISSUE THREAD

**Issue by agalpin** [shoreditch-ops/artillery#88]
I was attempting to save the DEBUG=http:response info into a file to be presented along with the results i have tried piping, redirecting but couldn't get it working.

There also doesn't appear to be an option for outputting these to a file.

Could you add support to allow piping or an option?

**Comment by hassy** [comment]
@agalpin You can make it work with: `DEBUG_FD=1 DEBUG=http:response artillery run myscript.yml > log.txt`

(This needs to be documented!)

**Comment by hassy** [comment]
Created https://github.com/shoreditch-ops/artillery/issues/95 - closing this for now.
