### ISSUE TITLE
HTTP Agent keepAlive option should be active for each request?

### ISSUE THREAD

**Issue by adrianocola** [shoreditch-ops/artillery#90]
I'm trying to run a quick test with 100 virtual users for 60 seconds against a simple node-express server that returns a simple hardcoded json. But the express server hangs and stops accepting new connections. When using other request generators (like apache ab) I can make more than 500 requests per second against this server, but with artillery I can't reach 100.

I noticed some ECONNRESET and EMFILE errors reported by artillery and discovered that artillery was filling my server limit of open files/sockets ( checked that with the command _lsof -i -n -P_ ) .

So I digged down to [artillery-core](https://github.com/shoreditch-ops/artillery-core) http engine and saw that it is always creating a new http.Agent with the keepAlive option for every request made, thus occupying a open socket slot FOR EACH REQUEST as long as artillery is running.

If I turn off http.Agent keepAlive (commenting them), I can make 500 requests per second against my server using artillery.

This is is a expected/desired behavior?

**Comment by hassy** [comment]
@adrianocola Yep, you're right, Artillery creates a socket for every virtual user by default to simulate real-world behavior, whereas `ab` opens a fixed number of connections.

The next release of Artillery will add extra flags to `quick` to allow a fixed number of connections and to allow specifying the number of requests to be sent on each connection (like in `ab`):

See here for more: https://github.com/shoreditch-ops/artillery/issues/54

**Comment by hassy** [comment]
@adrianocola gonna close this for now - but if you have any comments or questions feel free to post here or on the [gitter channel](https://gitter.im/shoreditch-ops/artillery)

**Comment by hhartz** [comment]
I'm experiencing a similar issue, I'm getting a ton of connections that are being kept alive ```netstat -nt | grep TIME_WAIT | wc -l
    4503```

**Comment by hassy** [comment]
That doesn’t necessarily indicate a problem. Could you give more details to
try to reproduce the issue?

**Comment by AndreaFranchini** [comment]
Windows 10
node v10.9.0
artillery v1.6.0-24

Express.js server (on remote host) that expose a post http api, accept a json and return an id.
Artillery arrivalRate 200, duration 30sec.

After some time artillery's output says "EADDRINUSE" and netstat shows thousands of connections in TIME_WAIT.

Let the research begin!!! I read tons of docs and issue, and i saw that:

artillery shuold close connections, without keep them alive
https://github.com/shoreditch-ops/artillery-core/pull/61

Try to use pool configuration
https://github.com/shoreditch-ops/artillery/issues/138

With pool config "All HTTP requests from all virtual users will be sent over the same 10 connections" cit docs
https://artillery.io/docs/http-reference/#fixed-connection-pool

So i've tested:

Artillery arrivalRate 10, duration 10sec.
config.http.pool: 10

Expected
- no EADDRINUSE (of course)
- netstat shuold shows max 10 connections

But nestat shows 100 connections in TIME_WAIT.

Even setting the keep alive header to 0
https://artillery.io/docs/http-reference/#set-headers

I've obtainined same result.

I want that artillery close the connections for:
- know if they grows up (my app-server can't respond fast enougth)
- can use high arrivalRate config

**Comment by hassy** [comment]
Thanks for the detail @adrianocola! I can confirm that the issue has been reproduced on this end and a fix is on its way.
