### ISSUE TITLE
What does p95 and p99 mean?

### ISSUE THREAD

**Issue by Dillybob92** [shoreditch-ops/artillery#91]
```
all scenarios completed
Complete report @ 2016-05-14T04:57:10.029Z
  Scenarios launched: 1000
  Scenarios completed: 1000
  Number of requests made: 2000
  RPS: 95.37
  Request latency:
    min: 0.1
    max: 7.2
    median: 0.2
    p95: 0.5
    p99: 1.3
  Scenario duration:
    min: 1000.4
    max: 1033.9
    median: 1001.1
    p95: 1003.1
    p99: 1007.5
  Codes:
    0: 2000
```

What exactly does p95 and p99 represent, and does RPS mean Requests Per Second? Just curious, thanks!

Edit: Btw, this is a websocket server. I'm trying to get the number of messages sent per second

**Comment by hassy** [comment]
@Dillybob92 RPS is requests per second (but with WS it means a message).

p95 is the 95th percentile latency, i.e. for 95 percent of virtual users in your report, the latency was 0.5ms or lower.

**Comment by Dillybob92** [comment]
@hassy Ohh I see. You got the Maths down then! I suck at Math, haha. Thanks for the response, love this module!!

**Comment by jszoja** [comment]
> @Dillybob92 RPS is requests per second (but with WS it means a message).
> 
> p95 is the 95th percentile latency, i.e. for 95 percent of virtual users in your report, the latency was 0.5ms or lower.

I couldn't find that info on the Artillery documentation page. Can we add it there?
https://www.artillery.io/docs
