### ISSUE TITLE
Accept variables from the command-line

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#93]
In many situations it would be useful to adjust some of the values in the `config` section from the command line (e.g. the target, or the load phases).

**Comment by enderv** [comment]
Easiest idea I have is a command line option where you pass in variable names and values. That option will cause the config to be preloaded as a string, sub the values, and then convert to an object to be passed in?


For example:
`--replace "foo=bar,test=thatThing"`

`
{
  "config": {
      "target": "http://127.0.0.1:3003",
      "phases": [
        {"duration": 10, "arrivalRate": 1}
      ]
  },
  "scenarios": [
    {
      "flow": [
        {"get": {"url": "/", "capture": {"xpath": "//", "as": "{{foo}}"}}},
        {"post": {"url": "/pets", "json": {"name": "Figo", "species": "{{test}}"}}}
      ]
    }
  ]
}`

`
{
  "config": {
      "target": "http://127.0.0.1:3003",
      "phases": [
        {"duration": 10, "arrivalRate": 1}
      ]
  },
  "scenarios": [
    {
      "flow": [
        {"get": {"url": "/", "capture": {"xpath": "//", "as": "bar"}}},
        {"post": {"url": "/pets", "json": {"name": "Figo", "species": "thatThing"}}}
      ]
    }
  ]
}`

**Comment by enderv** [comment]
And thinking this over some more realized why not just use a json object in the commandline with the values to replace. No idea if this will actually work but it would make it alot easier. Also realized I was using the same marker as the variables so maybe something like `{% name %}`

`--replace "{foo:"bar",test:"thatThing"}  `

 `{ "config": { "target": "http://127.0.0.1:3003", "phases": [ {"duration": 10, "arrivalRate": 1} ] }, "scenarios": [ { "flow": [ {"get": {"url": "/", "capture": {"xpath": "//", "as": "{%foo%}"}}}, {"post": {"url": "/pets", "json": {"name": "Figo", "species": "{%test%}"}}} ] } ] }`

**Comment by NickHongXin** [comment]
Can i know which artillery version supports '--replace' option?
Thanks

**Comment by jeffatnike** [comment]
What's the status of this idea? I'm looking to inject system environment variables into the script, not sure if there's an obvious solution, but it seems the `$environment` variable is stealing all of my searches.

**Comment by jeffatnike** [comment]
oh this? https://artillery.io/docs/cli-reference/#experimental-overrides

**Comment by hassy** [comment]
Both use cases are served by either `--overrides` or the new `-v` option (#446). Closing this as (almost) done.
