### ISSUE TITLE
Docs: document debug mode

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery#95]
- Document various `DEBUG` options
- Document how debug output can be saved to a file (https://github.com/shoreditch-ops/artillery/issues/88)
- Document how to enable it on Windows (e.g. `set DEBUG=http` and then `artillery run ...`)

**Comment by danielmihai** [comment]
Can you post a complete example of running an artillery test in debug mode, please ?

**Comment by hassy** [comment]
@danielmihai For HTTP: `DEBUG=http* artillery run myscript.json`

**Comment by danielmihai** [comment]
OK, worked. I had an error in the yml file that wasn't outputted as an error. it was in the flow section. 
More error info would be nice ;) 

Thanks!

**Comment by YsoL8** [comment]
Sorry to dig this out of its grave - but does not appear to be documented in the main docs.
It'd be super useful to have this as a newb, its just not exposed anywhere.
